const vocabData = {
    "Level 1": [
        { word: "淘气", pinyin: "táo qì", meaning: "naughty; mischievous" },
        { word: "惹", pinyin: "rě", meaning: "to provoke; to attract (troubles); to cause (problems)" },
        { word: "两肋插刀", pinyin: "liǎng lèi chā dāo", meaning: "to attach great importance to friendship; sacrifice oneself" },
        { word: "赵", pinyin: "zhào", meaning: "surname Zhao" },
        { word: "科技", pinyin: "kē jì", meaning: "science and technology" },
        { word: "来者不拒", pinyin: "lái zhě bù jù", meaning: "all comers welcome" },
        { word: "小事一桩", pinyin: "xiǎo shì yī zhuāng", meaning: "a piece of cake" },
        { word: "口头禅", pinyin: "kǒu tóu chán", meaning: "catchphrase; mantra" },
        { word: "人缘", pinyin: "rén yuán", meaning: "relations with other people" },
        { word: "性格", pinyin: "xìng gé", meaning: "nature; temperament; character" },
        { word: "直率", pinyin: "zhí shuài", meaning: "candid; frank" },
        { word: "得罪", pinyin: "dé zuì", meaning: "to offend" },
        { word: "别扭", pinyin: "biè niu", meaning: "awkward; uncomfortable" },
        { word: "争辩", pinyin: "zhēng biàn", meaning: "to dispute; wrangle" },
        { word: "即使", pinyin: "jí shǐ", meaning: "even if; even though" },
        { word: "冤枉", pinyin: "yuān wang", meaning: "to accuse wrongly; treat unjustly" },
        { word: "推荐", pinyin: "tuī jiàn", meaning: "to recommend" },
        { word: "捣乱", pinyin: "dǎo luàn", meaning: "to disturb; look for trouble" },
        { word: "瞬间", pinyin: "shùn jiān", meaning: "in an instant" },
        { word: "粘", pinyin: "zhān", meaning: "to stick; to glue" },
        { word: "兴致勃勃", pinyin: "xìng zhì bó bó", meaning: "in high spirits; full of zest" },
        { word: "狼狈", pinyin: "láng bèi", meaning: "in a difficult situation" },
        { word: "蛋液", pinyin: "dàn yè", meaning: "liquid of the egg" },
        { word: "讥讽", pinyin: "jī fěng", meaning: "to ridicule; to mock" },
        { word: "赌气", pinyin: "dǔ qì", meaning: "to act in a fit of pique" },
        { word: "嚷", pinyin: "rǎng", meaning: "to shout; blurt out" },
        { word: "小心翼翼", pinyin: "xiǎo xīn yì yì", meaning: "very carefully; prudent" },
        { word: "荧光笔", pinyin: "yíng guāng bǐ", meaning: "highlighter" },
        { word: "抵挡", pinyin: "dǐ dǎng", meaning: "to resist; withstand" },
        { word: "拉扯", pinyin: "lā che", meaning: "to pull; drag; raise a child" },
        { word: "手足无措", pinyin: "shǒu zú wú cuò", meaning: "at a loss what to do" },
        { word: "审案", pinyin: "shěn àn", meaning: "try a case" },
        { word: "律师", pinyin: "lǜ shī", meaning: "lawyer" },
        { word: "振振有词", pinyin: "zhèn zhèn yǒu cí", meaning: "argue with courage of convictions" },
        { word: "心虚", pinyin: "xīn xū", meaning: "guilty conscience" },
        { word: "哑口无言", pinyin: "yǎ kǒu wú yán", meaning: "speechless" },
        { word: "判决", pinyin: "pàn jué", meaning: "judgment; sentence" },
        { word: "泄", pinyin: "xiè", meaning: "to leak; divulge; vent" },
        { word: "葡萄", pinyin: "pú tao", meaning: "grape" },
        { word: "风俗", pinyin: "fēng sú", meaning: "social custom" },
        { word: "象征", pinyin: "xiàng zhēng", meaning: "symbol; symbolize" },
        { word: "辞旧迎新", pinyin: "cí jiù yíng xīn", meaning: "ring out the old; ring in the new" },
        { word: "燃放", pinyin: "rán fàng", meaning: "to set off (firecrackers)" },
        { word: "厄运", pinyin: "è yùn", meaning: "bad luck; misfortune" },
        { word: "瓶瓶罐罐", pinyin: "píng píng guàn guàn", meaning: "bottles and cans" },
        { word: "前夕", pinyin: "qián xī", meaning: "eve" },
        { word: "碗碟", pinyin: "wǎn dié", meaning: "bowls and plates" },
        { word: "预示", pinyin: "yù shì", meaning: "to indicate; foretell" },
        { word: "忙碌", pinyin: "máng lù", meaning: "busy" },
        { word: "兆头", pinyin: "zhào tou", meaning: "omen; sign" },
        { word: "遥远", pinyin: "yáo yuǎn", meaning: "distant; remote" },
        { word: "恭敬", gōng jìng: "respectful" },
        { word: "万事大吉", pinyin: "wàn shì dà jí", meaning: "all is well" },
        { word: "元旦", pinyin: "yuán dàn", meaning: "New Year's Day" },
        { word: "贼", pinyin: "zéi", meaning: "thief" },
        { word: "鱼尾纹", pinyin: "yú wěi wén", meaning: "crow's feet" },
        { word: "装饰", pinyin: "zhuāng shì", meaning: "decorate" },
        { word: "圣诞", pinyin: "shèng dàn", meaning: "Christmas" },
        { word: "格格不入", pinyin: "gé gé bù rù", meaning: "inharmonious; incompatible" },
        { word: "结婚", pinyin: "jié hūn", meaning: "to marry" },
        { word: "嫁", pinyin: "jià", meaning: "to marry off a daughter" },
        { word: "视讯", pinyin: "shì xùn", meaning: "video call" },
        { word: "沉默寡言", pinyin: "chén mò guǎ yán", meaning: "reticent; silent" },
        { word: "酷", pinyin: "kù", meaning: "cool" },
        { word: "副", pinyin: "fù", meaning: "classifier for facial expressions" },
        { word: "承诺", pinyin: "chéng nuò", meaning: "to promise" },
        { word: "歉意", pinyin: "qiàn yì", meaning: "apology" },
        { word: "蒸腾", pinyin: "zhēng téng", meaning: "to rise (vapor)" },
        { word: "围炉", pinyin: "wéi lú", meaning: "steamboat" },
        { word: "叽叽喳喳", pinyin: "jī jī zhā zhā", meaning: "chirp; chatter" },
        { word: "缺席", pinyin: "quē xí", meaning: "absent" },
        { word: "悦耳", pinyin: "yuè ěr", meaning: "sweet-sounding" },
        { word: "红枣", pinyin: "hóng zǎo", meaning: "red date" },
        { word: "儿媳妇", pinyin: "ér xí fu", meaning: "daughter-in-law" },
        { word: "莫名其妙", pinyin: "mò míng qí miào", meaning: "inexplicable; baffling" },
        { word: "疑惑", pinyin: "yí huò", meaning: "suspicion; puzzle over" },
        { word: "魅力", pinyin: "mèi lì", meaning: "charm; charisma" },
        { word: "博物馆", pinyin: "bó wù guǎn", meaning: "museum" },
        { word: "悠久", pinyin: "yōu jiǔ", meaning: "long (history/tradition)" },
        { word: "遗产", pinyin: "yí chǎn", meaning: "heritage" },
        { word: "巴刹", pinyin: "bā shā", meaning: "wet market" },
        { word: "同胞", pinyin: "tóng bāo", meaning: "fellow citizen" },
        { word: "融合", pinyin: "róng hé", meaning: "fusion; harmonize" },
        { word: "城堡", pinyin: "chéng bǎo", meaning: "castle" },
        { word: "皇宫", pinyin: "huáng gōng", meaning: "imperial palace" },
        { word: "时尚", pinyin: "shí shàng", meaning: "fashion" },
        { word: "流连忘返", pinyin: "liú lián wàng fǎn", meaning: "linger and forget to go home" },
        { word: "彩绘", pinyin: "cǎi huì", meaning: "painted designs" },
        { word: "娱乐", pinyin: "yú lè", meaning: "entertainment" },
        { word: "探索", pinyin: "tàn suǒ", meaning: "explore" },
        { word: "娘惹", pinyin: "niáng rě", meaning: "Nyonya" },
        { word: "拍摄", pinyin: "pāi shè", meaning: "to film/shoot" },
        { word: "平均", pinyin: "píng jūn", meaning: "average" },
        { word: "繁忙", pinyin: "fán máng", meaning: "busy; bustling" },
        { word: "闪耀", pinyin: "shǎn yào", meaning: "glitter; sparkle" },
        { word: "衡量", pinyin: "héng liáng", meaning: "measure; weigh" },
        { word: "覆盖", pinyin: "fù gài", meaning: "to cover" },
        { word: "玻璃", pinyin: "bō li", meaning: "glass" },
        { word: "瀑布", pinyin: "pú bù", meaning: "waterfall" },
        { word: "循环", pinyin: "xún huán", meaning: "to cycle; circulate" },
        { word: "谷", pinyin: "gǔ", meaning: "valley; grain" },
        { word: "株", pinyin: "zhū", meaning: "plant; classifier for trees" },
        { word: "设施", pinyin: "shè shī", meaning: "facilities" },
        { word: "蹦跳", pinyin: "bèng tiào", meaning: "to hop; jump" },
        { word: "甚至", pinyin: "shèn zhì", meaning: "even" },
        { word: "投降", pinyin: "tóu xiáng", meaning: "surrender" },
        { word: "自治", pinyin: "zì zhì", meaning: "autonomy" },
        { word: "棕色", pinyin: "zōng sè", meaning: "brown" },
        { word: "栏", lán: "fence; railing; column" },
        { word: "氧化", pinyin: "yǎng huà", meaning: "oxidize" },
        { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
        { word: "属于", pinyin: "shǔ yú", meaning: "belong to" },
        { word: "宁静", pinyin: "níng jìng", meaning: "tranquil" },
        { word: "坚持不懈", pinyin: "jiān chí bù xiè", meaning: "persevere unremittingly" },
        { word: "以礼待人", pinyin: "yǐ lǐ dài rén", meaning: "treat with courtesy" },
        { word: "开卷有益", pinyin: "kāi juàn yǒu yì", meaning: "reading is beneficial" },
        { word: "新颖", pinyin: "xīn yǐng", meaning: "new and original" },
        { word: "戏剧", pinyin: "xì jù", meaning: "drama" },
        { word: "工作坊", pinyin: "gōng zuò fāng", meaning: "workshop" },
        { word: "尴尬", pinyin: "gān gà", meaning: "awkward; embarrassed" },
        { word: "维护", pinyin: "wéi hù", meaning: "safeguard; maintain" },
        { word: "一帆风顺", pinyin: "yī fān fēng shùn", meaning: "smooth sailing" },
        { word: "友谊", pinyin: "yǒu yì", meaning: "friendship" },
        { word: "有效", pinyin: "yǒu xiào", meaning: "effective; valid" },
        { word: "策略", pinyin: "cè lüè", meaning: "strategy" },
        { word: "辅导员", pinyin: "fǔ dǎo yuán", meaning: "counsellor" },
        { word: "嘉宾", pinyin: "jiā bīn", meaning: "esteemed guest" },
        { word: "赖床", pinyin: "lài chuáng", meaning: "dawdle in bed" },
        { word: "催促", pinyin: "cuī cù", meaning: "to urge" },
        { word: "滋味", pinyin: "zī wèi", meaning: "taste; flavor" },
        { word: "哀求", pinyin: "āi qiú", meaning: "to plead" },
        { word: "硬着头皮", pinyin: "yìng zhe tou pí", meaning: "brace oneself to do something" },
        { word: "抡", pinyin: "lūn", meaning: "to swing/wave" },
        { word: "藤鞭", pinyin: "téng biān", meaning: "rattan cane" },
        { word: "挨打", pinyin: "ái dǎ", meaning: "take a beating" },
        { word: "女佣", pinyin: "nǚ yōng", meaning: "maid" },
        { word: "雨篷", pinyin: "yǔ péng", meaning: "rain cover" },
        { word: "泪痕", pinyin: "lèi hén", meaning: "tear stains" },
        { word: "早晨", pinyin: "zǎo chén", meaning: "early morning" },
        { word: "猛", pinyin: "měng", meaning: "fierce; sudden" },
        { word: "嗓子眼", pinyin: "sǎng zi yǎn", meaning: "throat" },
        { word: "允许", pinyin: "yǔ nǔ", meaning: "permit; allow" },
        { word: "讲究", pinyin: "jiǎng jiu", meaning: "pay attention to quality" },
        { word: "相貌", pinyin: "xiàng mào", meaning: "appearance" },
        { word: "何必", pinyin: "hé bì", meaning: "why should; no need" },
        { word: "记账", pinyin: "jì zhàng", meaning: "bookkeeping" },
        { word: "亏", pinyin: "kuī", meaning: "deficit; deficiency" },
        { word: "撇", pinyin: "piē", meaning: "cast away" },
        { word: "慢条斯理", pinyin: "màn tiáo sī lǐ", meaning: "unhurried; leisurely" },
        { word: "起航", pinyin: "qǐ háng", meaning: "set sail / take off" },
        { word: "焦急", pinyin: "jiāo jí", meaning: "anxious" },
        { word: "剩", pinyin: "shèng", meaning: "remain; left over" },
        { word: "牙膏", pinyin: "yá gāo", meaning: "toothpaste" },
        { word: "橡皮擦", pinyin: "xiàng pí cā", meaning: "eraser" },
        { word: "薯条", pinyin: "shǔ tiáo", meaning: "french fries" },
        { word: "番茄酱", pinyin: "fān qié jiàng", meaning: "ketchup" },
        { word: "偶尔", pinyin: "ǒu ěr", meaning: "occasionally" },
        { word: "评委", pinyin: "píng wěi", meaning: "judges" },
        { word: "晋级", pinyin: "jìn jí", meaning: "promotion; advance" },
        { word: "奖励", pinyin: "jiǎng lì", meaning: "reward" },
        { word: "获得", pinyin: "huò dé", meaning: "obtain; receive" },
        { word: "企业", pinyin: "qǐ yè", meaning: "enterprise; company" },
        { word: "牧场", pinyin: "mù chǎng", meaning: "pasture; ranch" },
        { word: "艘", pinyin: "sōu", meaning: "classifier for ships" },
        { word: "潜水", pinyin: "qián shuǐ", meaning: "to dive" },
        { word: "屁股", pinyin: "pì gǔ", meaning: "buttocks" },
        { word: "翘", pinyin: "qiào", meaning: "stick up; tilt" },
        { word: "仿佛", pinyin: "fǎng fú", meaning: "as if; seem" },
        { word: "潜水艇", pinyin: "qián shuǐ tǐng", meaning: "submarine" },
        { word: "确切", pinyin: "què qiè", meaning: "exact; definite" },
        { word: "浑身", pinyin: "hún shēn", meaning: "all over the body" },
        { word: "基因", pinyin: "jī yīn", meaning: "gene" },
        { word: "一哄而散", pinyin: "yī hòng ér sàn", meaning: "disperse in confusion" },
        { word: "颁布", pinyin: "bān bù", meaning: "to issue (laws)" },
        { word: "手势", pinyin: "shǒu shì", meaning: "gesture" },
        { word: "泛", pinyin: "fàn", meaning: "float; suffused with" },
        { word: "泡沫", pinyin: "pào mò", meaning: "foam; bubble" },
        { word: "伤脑筋", pinyin: "shāng nǎo jīn", meaning: "a real headache" },
        { word: "拜访", pinyin: "bài fǎng", meaning: "to visit" },
        { word: "漫步", pinyin: "màn bù", meaning: "wander; ramble" },
        { word: "中央", pinyin: "zhōng yāng", meaning: "central" },
        { word: "绞尽脑汁", pinyin: "jiǎo jìn nǎo zhī", meaning: "rack one's brains" },
        { word: "银行", pinyin: "yín háng", meaning: "bank" },
        { word: "华侨", pinyin: "huá qiáo", meaning: "overseas Chinese" },
        { word: "由衷", pinyin: "yóu zhōng", meaning: "heartfelt; sincere" },
        { word: "摩天大楼", pinyin: "mó tiān dà lóu", meaning: "skyscraper" },
        { word: "抨击", pinyin: "pēng jī", meaning: "attack (verbally)" },
        { word: "薄薄的", pinyin: "báo báo de", meaning: "thin" },
        { word: "挫折", pinyin: "cuò zhé", meaning: "setback" },
        { word: "油漆", pinyin: "yóu qī", meaning: "paint; lacquer" },
        { word: "栏杆", pinyin: "lán gān", meaning: "railing" },
        { word: "宿舍", pinyin: "sù shè", meaning: "dormitory" },
        { word: "凭", pinyin: "píng", meaning: "rely on" },
        { word: "订购", pinyin: "dìng gòu", meaning: "place an order" },
        { word: "欣慰", pinyin: "xīn wèi", meaning: "gratified" },
        { word: "塔台", pinyin: "tǎ tái", meaning: "control tower" },
        { word: "范围", pinyin: "fàn wéi", meaning: "range; scope" },
        { word: "特殊", pinyin: "tè shū", meaning: "special" },
        { word: "警惕", pinyin: "jǐng tì", meaning: "vigilant; alert" },
        { word: "失误", pinyin: "shī wù", meaning: "mistake" },
        { word: "不堪设想", pinyin: "bù kān shè xiǎng", meaning: "too horrible to contemplate" },
        { word: "脂肪", pinyin: "zhī fáng", meaning: "fat" },
        { word: "截至", pinyin: "jié zhì", meaning: "up to (a time)" },
        { word: "行驶", pinyin: "xíng shǐ", meaning: "to travel (vehicle)" },
        { word: "延误", pinyin: "yán wu", meaning: "delay" },
        { word: "稳定", pinyin: "wěn dìng", meaning: "steady; stable" },
        { word: "幕后", pinyin: "mù hòu", meaning: "behind the scenes" },
        { word: "贡献", pinyin: "gòng xiàn", meaning: "contribute" },
        { word: "明知山有虎，偏向虎山行", pinyin: "míng zhī shān yǒu hǔ...", meaning: "taking risks despite danger" },
        { word: "漏夜", pinyin: "lòu yè", meaning: "late at night" },
        { word: "轨道", pinyin: "guǐ dào", meaning: "track; orbit" },
        { word: "就绪", pinyin: "jiù xù", meaning: "ready; in order" },
        { word: "凌晨", pinyin: "líng chén", meaning: "early morning" },
        { word: "隧道", pinyin: "suì dào", meaning: "tunnel" },
        { word: "裂痕", pinyin: "liè hén", meaning: "crack; split" },
        { word: "扫描", pinyin: "sǎo miáo", meaning: "scan" },
        { word: "顺畅", pinyin: "shùn chàng", meaning: "fluent; smooth" },
        { word: "职业", pinyin: "zhí yè", meaning: "occupation; profession" },
        { word: "全力以赴", pinyin: "quán lì yǐ fù", meaning: "all-out effort" },
        { word: "故障", pinyin: "gù zhàng", meaning: "malfunction; fault" },
        { word: "岗位", pinyin: "gǎng wèi", meaning: "a post; job" },
        { word: "芝麻", pinyin: "zhī ma", meaning: "sesame" },
        { word: "新谣", pinyin: "xīn yáo", meaning: "Singapore Chinese songs" },
        { word: "朗朗上口", pinyin: "lǎng lǎng shàng kǒu", meaning: "catchy; easy to recite" },
        { word: "奉献", pinyin: "fèng xiàn", meaning: "dedicate; devote" },
        { word: "繁荣", pinyin: "fán róng", meaning: "prosperous" },
        { word: "平凡", pinyin: "píng fán", meaning: "ordinary" },
        { word: "光芒", pinyin: "guāng máng", meaning: "rays of light" }
    ]
};
