const vocabData = {
    "Level 1": [
        { word: "淘气", pinyin: "táo qì", meaning: "naughty; mischievous" },
        { word: "惹", pinyin: "rě", meaning: "to provoke; to attract (troubles); to cause (problems)" },
        { word: "两肋插刀", pinyin: "liǎng lèi chā dāo", meaning: "to attach great importance to friendship; sacrifice oneself" },
        { word: "赵", pinyin: "zhào", meaning: "surname Zhao" },
        { word: "科技", pinyin: "kē jì", meaning: "science and technology" },
        { word: "来者不拒", pinyin: "lái zhě bù jù", meaning: "all comers welcome" },
        { word: "小事一桩", pinyin: "xiǎo shì yī zhuāng", meaning: "a piece of cake" },
        { word: "口头禅", pinyin: "kǒu tóu chán", meaning: "catchphrase; mantra" },
        { word: "人缘", pinyin: "rén yuán", meaning: "relations with other people" },
        { word: "性格", pinyin: "xìng gé", meaning: "nature; temperament; character" },
        { word: "直率", pinyin: "zhí shuài", meaning: "candid; frank" },
        { word: "得罪", pinyin: "dé zuì", meaning: "to offend" },
        { word: "别扭", pinyin: "biè niu", meaning: "awkward; uncomfortable" },
        { word: "争辩", pinyin: "zhēng biàn", meaning: "to dispute; wrangle" },
        { word: "即使", pinyin: "jí shǐ", meaning: "even if; even though" },
        { word: "冤枉", pinyin: "yuān wang", meaning: "to accuse wrongly; treat unjustly" },
        { word: "推荐", pinyin: "tuī jiàn", meaning: "to recommend" },
        { word: "捣乱", pinyin: "dǎo luàn", meaning: "to disturb; look for trouble" },
        { word: "瞬间", pinyin: "shùn jiān", meaning: "in an instant" },
        { word: "粘", pinyin: "zhān", meaning: "to stick; to glue" },
        { word: "兴致勃勃", pinyin: "xìng zhì bó bó", meaning: "in high spirits; full of zest" },
        { word: "狼狈", pinyin: "láng bèi", meaning: "in a difficult situation" },
        { word: "蛋液", pinyin: "dàn yè", meaning: "liquid of the egg" },
        { word: "讥讽", pinyin: "jī fěng", meaning: "to ridicule; to mock" },
        { word: "赌气", pinyin: "dǔ qì", meaning: "to act in a fit of pique" },
        { word: "嚷", pinyin: "rǎng", meaning: "to shout; blurt out" },
        { word: "小心翼翼", pinyin: "xiǎo xīn yì yì", meaning: "very carefully; prudent" },
        { word: "荧光笔", pinyin: "yíng guāng bǐ", meaning: "highlighter" },
        { word: "抵挡", pinyin: "dǐ dǎng", meaning: "to resist; withstand" },
        { word: "拉扯", pinyin: "lā che", meaning: "to pull; drag; raise a child" },
        { word: "手足无措", pinyin: "shǒu zú wú cuò", meaning: "at a loss what to do" },
        { word: "审案", pinyin: "shěn àn", meaning: "try a case" },
        { word: "律师", pinyin: "lǜ shī", meaning: "lawyer" },
        { word: "振振有词", pinyin: "zhèn zhèn yǒu cí", meaning: "argue with courage of convictions" },
        { word: "心虚", pinyin: "xīn xū", meaning: "guilty conscience" },
        { word: "哑口无言", pinyin: "yǎ kǒu wú yán", meaning: "speechless" },
        { word: "判决", pinyin: "pàn jué", meaning: "judgment; sentence" },
        { word: "泄", pinyin: "xiè", meaning: "to leak; divulge; vent" },
        { word: "葡萄", pinyin: "pú tao", meaning: "grape" },
        { word: "风俗", pinyin: "fēng sú", meaning: "social custom" },
        { word: "象征", pinyin: "xiàng zhēng", meaning: "symbol; symbolize" },
        { word: "辞旧迎新", pinyin: "cí jiù yíng xīn", meaning: "ring out the old; ring in the new" },
        { word: "燃放", pinyin: "rán fàng", meaning: "to set off (firecrackers)" },
        { word: "厄运", pinyin: "è yùn", meaning: "bad luck; misfortune" },
        { word: "瓶瓶罐罐", pinyin: "píng píng guàn guàn", meaning: "bottles and cans" },
        { word: "前夕", pinyin: "qián xī", meaning: "eve" },
        { word: "碗碟", pinyin: "wǎn dié", meaning: "bowls and plates" },
        { word: "预示", pinyin: "yù shì", meaning: "to indicate; foretell" },
        { word: "忙碌", pinyin: "máng lù", meaning: "busy" },
        { word: "兆头", pinyin: "zhào tou", meaning: "omen; sign" },
        { word: "遥远", pinyin: "yáo yuǎn", meaning: "distant; remote" },
        { word: "恭敬", gōng jìng: "respectful" },
        { word: "万事大吉", pinyin: "wàn shì dà jí", meaning: "all is well" },
        { word: "元旦", pinyin: "yuán dàn", meaning: "New Year's Day" },
        { word: "贼", pinyin: "zéi", meaning: "thief" },
        { word: "鱼尾纹", pinyin: "yú wěi wén", meaning: "crow's feet" },
        { word: "装饰", pinyin: "zhuāng shì", meaning: "decorate" },
        { word: "圣诞", pinyin: "shèng dàn", meaning: "Christmas" },
        { word: "格格不入", pinyin: "gé gé bù rù", meaning: "inharmonious; incompatible" },
        { word: "结婚", pinyin: "jié hūn", meaning: "to marry" },
        { word: "嫁", pinyin: "jià", meaning: "to marry off a daughter" },
        { word: "视讯", pinyin: "shì xùn", meaning: "video call" },
        { word: "沉默寡言", pinyin: "chén mò guǎ yán", meaning: "reticent; silent" },
        { word: "酷", pinyin: "kù", meaning: "cool" },
        { word: "副", pinyin: "fù", meaning: "classifier for facial expressions" },
        { word: "承诺", pinyin: "chéng nuò", meaning: "to promise" },
        { word: "歉意", pinyin: "qiàn yì", meaning: "apology" },
        { word: "蒸腾", pinyin: "zhēng téng", meaning: "to rise (vapor)" },
        { word: "围炉", pinyin: "wéi lú", meaning: "steamboat" },
        { word: "叽叽喳喳", pinyin: "jī jī zhā zhā", meaning: "chirp; chatter" },
        { word: "缺席", pinyin: "quē xí", meaning: "absent" },
        { word: "悦耳", pinyin: "yuè ěr", meaning: "sweet-sounding" },
        { word: "红枣", pinyin: "hóng zǎo", meaning: "red date" },
        { word: "儿媳妇", pinyin: "ér xí fu", meaning: "daughter-in-law" },
        { word: "莫名其妙", pinyin: "mò míng qí miào", meaning: "inexplicable; baffling" },
        { word: "疑惑", pinyin: "yí huò", meaning: "suspicion; puzzle over" },
        { word: "魅力", pinyin: "mèi lì", meaning: "charm; charisma" },
        { word: "博物馆", pinyin: "bó wù guǎn", meaning: "museum" },
        { word: "悠久", pinyin: "yōu jiǔ", meaning: "long (history/tradition)" },
        { word: "遗产", pinyin: "yí chǎn", meaning: "heritage" },
        { word: "巴刹", pinyin: "bā shā", meaning: "wet market" },
        { word: "同胞", pinyin: "tóng bāo", meaning: "fellow citizen" },
        { word: "融合", pinyin: "róng hé", meaning: "fusion; harmonize" },
        { word: "城堡", pinyin: "chéng bǎo", meaning: "castle" },
        { word: "皇宫", pinyin: "huáng gōng", meaning: "imperial palace" },
        { word: "时尚", pinyin: "shí shàng", meaning: "fashion" },
        { word: "流连忘返", pinyin: "liú lián wàng fǎn", meaning: "linger and forget to go home" },
        { word: "彩绘", pinyin: "cǎi huì", meaning: "painted designs" },
        { word: "娱乐", pinyin: "yú lè", meaning: "entertainment" },
        { word: "探索", pinyin: "tàn suǒ", meaning: "explore" },
        { word: "娘惹", pinyin: "niáng rě", meaning: "Nyonya" },
        { word: "拍摄", pinyin: "pāi shè", meaning: "to film/shoot" },
        { word: "平均", pinyin: "píng jūn", meaning: "average" },
        { word: "繁忙", pinyin: "fán máng", meaning: "busy; bustling" },
        { word: "闪耀", pinyin: "shǎn yào", meaning: "glitter; sparkle" },
        { word: "衡量", pinyin: "héng liáng", meaning: "measure; weigh" },
        { word: "覆盖", pinyin: "fù gài", meaning: "to cover" },
        { word: "玻璃", pinyin: "bō li", meaning: "glass" },
        { word: "瀑布", pinyin: "pú bù", meaning: "waterfall" },
        { word: "循环", pinyin: "xún huán", meaning: "to cycle; circulate" },
        { word: "谷", pinyin: "gǔ", meaning: "valley; grain" },
        { word: "株", pinyin: "zhū", meaning: "plant; classifier for trees" },
        { word: "设施", pinyin: "shè shī", meaning: "facilities" },
        { word: "蹦跳", pinyin: "bèng tiào", meaning: "to hop; jump" },
        { word: "甚至", pinyin: "shèn zhì", meaning: "even" },
        { word: "投降", pinyin: "tóu xiáng", meaning: "surrender" },
        { word: "自治", pinyin: "zì zhì", meaning: "autonomy" },
        { word: "棕色", pinyin: "zōng sè", meaning: "brown" },
        { word: "栏", lán: "fence; railing; column" },
        { word: "氧化", pinyin: "yǎng huà", meaning: "oxidize" },
        { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
        { word: "属于", pinyin: "shǔ yú", meaning: "belong to" },
        { word: "宁静", pinyin: "níng jìng", meaning: "tranquil" },
        { word: "坚持不懈", pinyin: "jiān chí bù xiè", meaning: "persevere unremittingly" },
        { word: "以礼待人", pinyin: "yǐ lǐ dài rén", meaning: "treat with courtesy" },
        { word: "开卷有益", pinyin: "kāi juàn yǒu yì", meaning: "reading is beneficial" },
        { word: "新颖", pinyin: "xīn yǐng", meaning: "new and original" },
        { word: "戏剧", pinyin: "xì jù", meaning: "drama" },
        { word: "工作坊", pinyin: "gōng zuò fāng", meaning: "workshop" },
        { word: "尴尬", pinyin: "gān gà", meaning: "awkward; embarrassed" },
        { word: "维护", pinyin: "wéi hù", meaning: "safeguard; maintain" },
        { word: "一帆风顺", pinyin: "yī fān fēng shùn", meaning: "smooth sailing" },
        { word: "友谊", pinyin: "yǒu yì", meaning: "friendship" },
        { word: "有效", pinyin: "yǒu xiào", meaning: "effective; valid" },
        { word: "策略", pinyin: "cè lüè", meaning: "strategy" },
        { word: "辅导员", pinyin: "fǔ dǎo yuán", meaning: "counsellor" },
        { word: "嘉宾", pinyin: "jiā bīn", meaning: "esteemed guest" },
        { word: "赖床", pinyin: "lài chuáng", meaning: "dawdle in bed" },
        { word: "催促", pinyin: "cuī cù", meaning: "to urge" },
        { word: "滋味", pinyin: "zī wèi", meaning: "taste; flavor" },
        { word: "哀求", pinyin: "āi qiú", meaning: "to plead" },
        { word: "硬着头皮", pinyin: "yìng zhe tou pí", meaning: "brace oneself to do something" },
        { word: "抡", pinyin: "lūn", meaning: "to swing/wave" },
        { word: "藤鞭", pinyin: "téng biān", meaning: "rattan cane" },
        { word: "挨打", pinyin: "ái dǎ", meaning: "take a beating" },
        { word: "女佣", pinyin: "nǚ yōng", meaning: "maid" },
        { word: "雨篷", pinyin: "yǔ péng", meaning: "rain cover" },
        { word: "泪痕", pinyin: "lèi hén", meaning: "tear stains" },
        { word: "早晨", pinyin: "zǎo chén", meaning: "early morning" },
        { word: "猛", pinyin: "měng", meaning: "fierce; sudden" },
        { word: "嗓子眼", pinyin: "sǎng zi yǎn", meaning: "throat" },
        { word: "允许", pinyin: "yǔ nǔ", meaning: "permit; allow" },
        { word: "讲究", pinyin: "jiǎng jiu", meaning: "pay attention to quality" },
        { word: "相貌", pinyin: "xiàng mào", meaning: "appearance" },
        { word: "何必", pinyin: "hé bì", meaning: "why should; no need" },
        { word: "记账", pinyin: "jì zhàng", meaning: "bookkeeping" },
        { word: "亏", pinyin: "kuī", meaning: "deficit; deficiency" },
        { word: "撇", pinyin: "piē", meaning: "cast away" },
        { word: "慢条斯理", pinyin: "màn tiáo sī lǐ", meaning: "unhurried; leisurely" },
        { word: "起航", pinyin: "qǐ háng", meaning: "set sail / take off" },
        { word: "焦急", pinyin: "jiāo jí", meaning: "anxious" },
        { word: "剩", pinyin: "shèng", meaning: "remain; left over" },
        { word: "牙膏", pinyin: "yá gāo", meaning: "toothpaste" },
        { word: "橡皮擦", pinyin: "xiàng pí cā", meaning: "eraser" },
        { word: "薯条", pinyin: "shǔ tiáo", meaning: "french fries" },
        { word: "番茄酱", pinyin: "fān qié jiàng", meaning: "ketchup" },
        { word: "偶尔", pinyin: "ǒu ěr", meaning: "occasionally" },
        { word: "评委", pinyin: "píng wěi", meaning: "judges" },
        { word: "晋级", pinyin: "jìn jí", meaning: "promotion; advance" },
        { word: "奖励", pinyin: "jiǎng lì", meaning: "reward" },
        { word: "获得", pinyin: "huò dé", meaning: "obtain; receive" },
        { word: "企业", pinyin: "qǐ yè", meaning: "enterprise; company" },
        { word: "牧场", pinyin: "mù chǎng", meaning: "pasture; ranch" },
        { word: "艘", pinyin: "sōu", meaning: "classifier for ships" },
        { word: "潜水", pinyin: "qián shuǐ", meaning: "to dive" },
        { word: "屁股", pinyin: "pì gǔ", meaning: "buttocks" },
        { word: "翘", pinyin: "qiào", meaning: "stick up; tilt" },
        { word: "仿佛", pinyin: "fǎng fú", meaning: "as if; seem" },
        { word: "潜水艇", pinyin: "qián shuǐ tǐng", meaning: "submarine" },
        { word: "确切", pinyin: "què qiè", meaning: "exact; definite" },
        { word: "浑身", pinyin: "hún shēn", meaning: "all over the body" },
        { word: "基因", pinyin: "jī yīn", meaning: "gene" },
        { word: "一哄而散", pinyin: "yī hòng ér sàn", meaning: "disperse in confusion" },
        { word: "颁布", pinyin: "bān bù", meaning: "to issue (laws)" },
        { word: "手势", pinyin: "shǒu shì", meaning: "gesture" },
        { word: "泛", pinyin: "fàn", meaning: "float; suffused with" },
        { word: "泡沫", pinyin: "pào mò", meaning: "foam; bubble" },
        { word: "伤脑筋", pinyin: "shāng nǎo jīn", meaning: "a real headache" },
        { word: "拜访", pinyin: "bài fǎng", meaning: "to visit" },
        { word: "漫步", pinyin: "màn bù", meaning: "wander; ramble" },
        { word: "中央", pinyin: "zhōng yāng", meaning: "central" },
        { word: "绞尽脑汁", pinyin: "jiǎo jìn nǎo zhī", meaning: "rack one's brains" },
        { word: "银行", pinyin: "yín háng", meaning: "bank" },
        { word: "华侨", pinyin: "huá qiáo", meaning: "overseas Chinese" },
        { word: "由衷", pinyin: "yóu zhōng", meaning: "heartfelt; sincere" },
        { word: "摩天大楼", pinyin: "mó tiān dà lóu", meaning: "skyscraper" },
        { word: "抨击", pinyin: "pēng jī", meaning: "attack (verbally)" },
        { word: "薄薄的", pinyin: "báo báo de", meaning: "thin" },
        { word: "挫折", pinyin: "cuò zhé", meaning: "setback" },
        { word: "油漆", pinyin: "yóu qī", meaning: "paint; lacquer" },
        { word: "栏杆", pinyin: "lán gān", meaning: "railing" },
        { word: "宿舍", pinyin: "sù shè", meaning: "dormitory" },
        { word: "凭", pinyin: "píng", meaning: "rely on" },
        { word: "订购", pinyin: "dìng gòu", meaning: "place an order" },
        { word: "欣慰", pinyin: "xīn wèi", meaning: "gratified" },
        { word: "塔台", pinyin: "tǎ tái", meaning: "control tower" },
        { word: "范围", pinyin: "fàn wéi", meaning: "range; scope" },
        { word: "特殊", pinyin: "tè shū", meaning: "special" },
        { word: "警惕", pinyin: "jǐng tì", meaning: "vigilant; alert" },
        { word: "失误", pinyin: "shī wù", meaning: "mistake" },
        { word: "不堪设想", pinyin: "bù kān shè xiǎng", meaning: "too horrible to contemplate" },
        { word: "脂肪", pinyin: "zhī fáng", meaning: "fat" },
        { word: "截至", pinyin: "jié zhì", meaning: "up to (a time)" },
        { word: "行驶", pinyin: "xíng shǐ", meaning: "to travel (vehicle)" },
        { word: "延误", pinyin: "yán wu", meaning: "delay" },
        { word: "稳定", pinyin: "wěn dìng", meaning: "steady; stable" },
        { word: "幕后", pinyin: "mù hòu", meaning: "behind the scenes" },
        { word: "贡献", pinyin: "gòng xiàn", meaning: "contribute" },
        { word: "明知山有虎，偏向虎山行", pinyin: "míng zhī shān yǒu hǔ...", meaning: "taking risks despite danger" },
        { word: "漏夜", pinyin: "lòu yè", meaning: "late at night" },
        { word: "轨道", pinyin: "guǐ dào", meaning: "track; orbit" },
        { word: "就绪", pinyin: "jiù xù", meaning: "ready; in order" },
        { word: "凌晨", pinyin: "líng chén", meaning: "early morning" },
        { word: "隧道", pinyin: "suì dào", meaning: "tunnel" },
        { word: "裂痕", pinyin: "liè hén", meaning: "crack; split" },
        { word: "扫描", pinyin: "sǎo miáo", meaning: "scan" },
        { word: "顺畅", pinyin: "shùn chàng", meaning: "fluent; smooth" },
        { word: "职业", pinyin: "zhí yè", meaning: "occupation; profession" },
        { word: "全力以赴", pinyin: "quán lì yǐ fù", meaning: "all-out effort" },
        { word: "故障", pinyin: "gù zhàng", meaning: "malfunction; fault" },
        { word: "岗位", pinyin: "gǎng wèi", meaning: "a post; job" },
        { word: "芝麻", pinyin: "zhī ma", meaning: "sesame" },
        { word: "新谣", pinyin: "xīn yáo", meaning: "Singapore Chinese songs" },
        { word: "朗朗上口", pinyin: "lǎng lǎng shàng kǒu", meaning: "catchy; easy to recite" },
        { word: "奉献", pinyin: "fèng xiàn", meaning: "dedicate; devote" },
        { word: "繁荣", pinyin: "fán róng", meaning: "prosperous" },
        { word: "平凡", pinyin: "píng fán", meaning: "ordinary" },
        { word: "光芒", pinyin: "guāng máng", meaning: "rays of light" }
    ],
    "Level 2": [
        { word: "犹豫", pinyin: "yóu yù", meaning: "to hesitate" },
        { word: "不分青红皂白", pinyin: "bù fēn qīng hóng zào bái", meaning: "not to distinguish between right and wrong" },
        { word: "教训", pinyin: "jiāo xun", meaning: "lesson; to lecture somebody" },
        { word: "叛逆", pinyin: "pàn nì", meaning: "to rebel; a rebel" },
        { word: "委屈", pinyin: "wěi qu", meaning: "to feel wronged; grievance" },
        { word: "内疚", pinyin: "nèi jiù", meaning: "guilty conscience; feel guilt" },
        { word: "不妨", pinyin: "bù fáng", meaning: "might as well" },
        { word: "匿名", pinyin: "nì míng", meaning: "anonymous" },
        { word: "监督", pinyin: "jiān dū", meaning: "to supervise; control" },
        { word: "代沟", pinyin: "dài gōu", meaning: "generation gap" },
        { word: "疏远", pinyin: "shū yuǎn", meaning: "to drift apart; estranged" },
        { word: "上瘾", pinyin: "shàng yǐn", meaning: "to become addicted" },
        { word: "崇拜", pinyin: "chóng bài", meaning: "to worship; adoration" },
        { word: "碰钉子", pinyin: "pèng dīng zi", meaning: "to meet with a rebuff" },
        { word: "抽屉", pinyin: "chōu ti", meaning: "drawer" },
        { word: "掀", pinyin: "xiān", meaning: "to lift; to raise" },
        { word: "写稿", pinyin: "xiě gǎo", meaning: "to write an article" },
        { word: "搜查", pinyin: "sōu chá", meaning: "to search; ransack" },
        { word: "愤怒", pinyin: "fèn nù", meaning: "angry; indignant" },
        { word: "抗议", pinyin: "kàng yì", meaning: "to protest" },
        { word: "约束", pinyin: "yuē shù", meaning: "to restrict; constrain" },
        { word: "尊重", pinyin: "zūn zhòng", meaning: "to respect" },
        { word: "吵架", pinyin: "chǎo jià", meaning: "to quarrel" },
        { word: "酸", pinyin: "suān", meaning: "sour; tart" },
        { word: "催", pinyin: "cuī", meaning: "to urge; to prompt" },
        { word: "干脆", pinyin: "gān cuì", meaning: "straightforward; clear-cut" },
        { word: "承认", pinyin: "chéng rèn", meaning: "to admit" },
        { word: "具体", pinyin: "jù tǐ", meaning: "concrete; specific" },
        { word: "何况", pinyin: "hé kuàng", meaning: "much less; let alone" },
        { word: "歉意", pinyin: "qiàn yì", meaning: "apology; regret" },
        { word: "激动", pinyin: "jī dòng", meaning: "moved emotionally; excited" },
        { word: "增进", pinyin: "zēng jìn", meaning: "to promote; enhance" },
        { word: "踏", pinyin: "tà", meaning: "to tread; stamp" },
        { word: "糟糕", pinyin: "zāo gāo", meaning: "too bad; terrible" },
        { word: "诺言", pinyin: "nuò yán", meaning: "promise" },
        { word: "实现", pinyin: "shí xiàn", meaning: "to achieve; implement" },
        { word: "仿佛", pinyin: "fǎng fú", meaning: "to seem; as if" },
        { word: "暂时", pinyin: "zàn shí", meaning: "temporary" },
        { word: "普遍", pinyin: "pǔ biàn", meaning: "universal; general" },
        { word: "代替", pinyin: "dài tì", meaning: "to replace" },
        { word: "扩大", pinyin: "kuò dà", meaning: "to expand" },
        { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
        { word: "劝慰", pinyin: "quàn wèi", meaning: "to console; soothe" },
        { word: "掏", pinyin: "tāo", meaning: "to fish out (from pocket)" },
        { word: "残酷", pinyin: "cán kù", meaning: "cruel" },
        { word: "观察", pinyin: "guān chá", meaning: "to observe" },
        { word: "对应", pinyin: "duì yìng", meaning: "to correspond" },
        { word: "丰富", pinyin: "fēng fù", meaning: "rich; plentiful" },
        { word: "查询", pinyin: "chá xún", meaning: "to inquire about" },
        { word: "若干", pinyin: "ruò gān", meaning: "a certain number" },
        { word: "跟踪", pinyin: "gēn zōng", meaning: "to follow; tail" },
        { word: "输入", pinyin: "shū rù", meaning: "to input" },
        { word: "点击", pinyin: "diǎn jī", meaning: "to click" },
        { word: "联系", pinyin: "lián xì", meaning: "connection; contact" },
        { word: "功能", pinyin: "gōng néng", meaning: "function; capability" },
        { word: "淙淙", pinyin: "cóng cóng", meaning: "gurgling" },
        { word: "幢", pinyin: "zhuàng", meaning: "classifier for buildings" },
        { word: "榕树", pinyin: "róng shù", meaning: "banyan tree" },
        { word: "茂密", pinyin: "mào mì", meaning: "dense; lush" },
        { word: "延伸", pinyin: "yán shēn", meaning: "to extend" },
        { word: "翠绿", pinyin: "cuì lǜ", meaning: "jade green" },
        { word: "扁", pinyin: "biǎn", meaning: "flat" },
        { word: "记录", pinyin: "jì lù", meaning: "to record" },
        { word: "隐藏", pinyin: "yǐn cáng", meaning: "to hide; conceal" },
        { word: "我行我素", pinyin: "wǒ xíng wǒ sù", meaning: "to continue in one's own way" },
        { word: "效果", pinyin: "xiào guǒ", meaning: "result; effect" },
        { word: "非凡", pinyin: "fēi fán", meaning: "extraordinary" },
        { word: "堪称", pinyin: "kān chēng", meaning: "can be rated as" },
        { word: "抚摸", pinyin: "fǔ mō", meaning: "to caress; stroke" },
        { word: "感叹", pinyin: "gǎn tàn", meaning: "to sigh with feeling" },
        { word: "雄伟", pinyin: "xióng wěi", meaning: "grand; imposing" },
        { word: "尤其", pinyin: "yóu qí", meaning: "especially" },
        { word: "巧妙", pinyin: "qiǎo miào", meaning: "ingenious; clever" },
        { word: "独一无二", pinyin: "dú yī wú èr", meaning: "unique and unmatched" },
        { word: "闻名", pinyin: "wén míng", meaning: "famous" },
        { word: "栽种", pinyin: "zāi zhòng", meaning: "to plant" },
        { word: "排列", pinyin: "pái liè", meaning: "to arrange" },
        { word: "欣赏", pinyin: "xīn shǎng", meaning: "to appreciate" },
        { word: "赞叹", pinyin: "zàn tàn", meaning: "praise; gasp in admiration" },
        { word: "奇迹", pinyin: "qí jì", meaning: "miracle" },
        { word: "心旷神怡", pinyin: "xīn kuàng shén yí", meaning: "carefree and happy" },
        { word: "粗糙", pinyin: "cū cāo", meaning: "coarse; rough" },
        { word: "威武", pinyin: "wēi wǔ", meaning: "powerful; mighty" },
        { word: "丘陵", pinyin: "qiū líng", meaning: "hills" },
        { word: "挺拔", pinyin: "tǐng bá", meaning: "tall and straight" },
        { word: "慷慨", pinyin: "kāng kǎi", meaning: "generous" },
        { word: "窝", pinyin: "wō", meaning: "nest" },
        { word: "幽默", pinyin: "yōu mò", meaning: "humorous" },
        { word: "奇特", pinyin: "qí tè", meaning: "peculiar; odd" },
        { word: "闪烁", pinyin: "shǎn shuò", meaning: "twinkle; flicker" },
        { word: "造型", pinyin: "zào xíng", meaning: "modeling; design" },
        { word: "启发", pinyin: "qǐ fā", meaning: "to enlighten; inspire" },
        { word: "不仅", pinyin: "bù jǐn", meaning: "not only" },
        { word: "生活", pinyin: "shēng huó", meaning: "life; activity" },
        { word: "奋斗", pinyin: "fèn dòu", meaning: "strive; struggle" },
        { word: "含义", pinyin: "hán yì", meaning: "meaning; implication" },
        { word: "蒸", pinyin: "zhēng", meaning: "to steam; evaporate" },
        { word: "世纪", pinyin: "shì jì", meaning: "century" },
        { word: "寸", pinyin: "cùn", meaning: "inch" },
        { word: "刺激", pinyin: "cì jī", meaning: "to provoke; irritate" },
        { word: "概念", pinyin: "gài niàn", meaning: "concept; idea" },
        { word: "怀念", pinyin: "huái niàn", meaning: "to cherish memory" },
        { word: "热忱", pinyin: "rè chén", meaning: "zeal; enthusiasm" },
        { word: "形容", pinyin: "xíng róng", meaning: "to describe" },
        { word: "散发", pinyin: "sàn fā", meaning: "to emit; distribute" },
        { word: "气息", pinyin: "qì xī", meaning: "scent; breath" },
        { word: "浓郁", pinyin: "nóng yù", meaning: "rich; strong scent" },
        { word: "抒发", pinyin: "shū fā", meaning: "to express (emotion)" },
        { word: "振奋", pinyin: "zhèn fèn", meaning: "raise spirits" },
        { word: "昂首", pinyin: "áng shǒu", meaning: "hold head high" },
        { word: "挺胸", pinyin: "tǐng xiōng", meaning: "throw out chest" },
        { word: "辉煌", pinyin: "huī huáng", meaning: "splendid; glorious" },
        { word: "告诫", pinyin: "gào jiè", meaning: "to warn" },
        { word: "勉励", pinyin: "miǎn lì", meaning: "to encourage" },
        { word: "茁壮", pinyin: "zhuó zhuàng", meaning: "healthy and strong" },
        { word: "婆娑", pinyin: "pó suō", meaning: "to dance; whirl" },
        { word: "婀娜多姿", pinyin: "ē nuó duō zī", meaning: "graceful; elegant" },
        { word: "饱经风霜", pinyin: "bǎo jīng fēng shuāng", meaning: "weather-beaten" },
        { word: "移民", pinyin: "yí mín", meaning: "immigrate" },
        { word: "衰老", pinyin: "shuāi lǎo", meaning: "to age" },
        { word: "兴盛", pinyin: "xīng shèng", meaning: "flourish; thrive" }
    ],
    "Level 3": [
        { word: "良好", pinyin: "liáng hǎo", meaning: "good" },
        { word: "人际", pinyin: "rén jì", meaning: "human relationships" },
        { word: "坦率", pinyin: "tǎn shuài", meaning: "frank" },
        { word: "隐瞒", pinyin: "yǐn mán", meaning: "to conceal" },
        { word: "粗鲁", pinyin: "cū lǔ", meaning: "coarse/rude" },
        { word: "分歧", pinyin: "fēn qí", meaning: "divergent" },
        { word: "矛盾", pinyin: "máo dùn", meaning: "contradiction/conflict" },
        { word: "措施", pinyin: "cuò shī", meaning: "measure" },
        { word: "彼此", pinyin: "bǐ cǐ", meaning: "each other" },
        { word: "诀窍", pinyin: "jué qiào", meaning: "tips/hacks" },
        { word: "融洽", pinyin: "róng qià", meaning: "harmonious" },
        { word: "聆听", pinyin: "líng tīng", meaning: "to listen (respectfully)" },
        { word: "死党", pinyin: "sǐ dǎng", meaning: "best friends" },
        { word: "橱窗", pinyin: "chú chuāng", meaning: "display window" },
        { word: "强迫", pinyin: "qiǎng pò", meaning: "to force" },
        { word: "狭窄", pinyin: "xiá zhǎi", meaning: "narrow" },
        { word: "铅笔盒", pinyin: "qiān bǐ hé", meaning: "pencil case" },
        { word: "捻", pinyin: "niǎn", meaning: "to pinch" },
        { word: "抿", pinyin: "mǐn", meaning: "purse up (lips)" },
        { word: "肺炎", pinyin: "fèi yán", meaning: "pneumonia" },
        { word: "纸屑", pinyin: "zhǐ xiè", meaning: "scraps of paper" },
        { word: "肿瘤", pinyin: "zhǒng liú", meaning: "tumor" },
        { word: "癌症", pinyin: "ái zhèng", meaning: "cancer" },
        { word: "徒劳无功", pinyin: "tú láo wú gōng", meaning: "to work to no avail (idiom)" },
        { word: "擦拭", pinyin: "cā shì", meaning: "to wipe clean" },
        { word: "某", pinyin: "mǒu", meaning: "some" },
        { word: "苍白", pinyin: "cāng bái", meaning: "pale" },
        { word: "鼓掌", pinyin: "gǔ zhǎng", meaning: "to applaud" },
        { word: "忠实", pinyin: "zhōng shí", meaning: "faithful" },
        { word: "不同寻常", pinyin: "bù tóng xún cháng", meaning: "unusual" },
        { word: "痊愈", pinyin: "quán yù", meaning: "to recover completely" },
        { word: "清晰", pinyin: "qīng xī", meaning: "clear" },
        { word: "调剂", pinyin: "tiáo jì", meaning: "to adjust" },
        { word: "目睹", pinyin: "mù dǔ", meaning: "to witness" },
        { word: "鄙夷", pinyin: "bǐ yí", meaning: "to despise" },
        { word: "流淌", pinyin: "liú tǎng", meaning: "to flow" },
        { word: "窗帘", pinyin: "chuāng lián", meaning: "window curtains" },
        { word: "封", pinyin: "fēng", meaning: "to seal" },
        { word: "提心吊胆", pinyin: "tí xīn diào dǎn", meaning: "to be very scared and on edge" },
        { word: "古董", pinyin: "gǔ dǒng", meaning: "antique" },
        { word: "衡量", pinyin: "héng liáng", meaning: "to weigh" },
        { word: "纯洁", pinyin: "chún jié", meaning: "pure" },
        { word: "蔬菜", pinyin: "shū cài", meaning: "vegetables" },
        { word: "麦片", pinyin: "mài piàn", meaning: "oatmeal" },
        { word: "蛋白质", pinyin: "dàn bái zhì", meaning: "protein" },
        { word: "睡眠", pinyin: "shuì mián", meaning: "sleep (noun)" },
        { word: "频率", pinyin: "pín lǜ", meaning: "frequency" },
        { word: "体魄", pinyin: "tǐ pò", meaning: "physique" },
        { word: "韵律", pinyin: "yù nǜ", meaning: "rhythm/cadence" },
        { word: "汲取", pinyin: "jí qǔ", meaning: "to draw/absorb" },
        { word: "敞开", pinyin: "chǎng kāi", meaning: "to open wide" },
        { word: "心扉", pinyin: "xīn fēi", meaning: "door of heart" },
        { word: "缔造", pinyin: "dì zào", meaning: "to create/establish" },
        { word: "聊天", pinyin: "liáo tiān", meaning: "to chat" },
        { word: "郊外", pinyin: "jiāo wài", meaning: "outskirts" },
        { word: "淋漓", pinyin: "lín lí", meaning: "dripping wet" },
        { word: "手札", pinyin: "shǒu zhá", meaning: "personal letter" },
        { word: "抒发", pinyin: "shū fā", meaning: "to express (emotion)" },
        { word: "歇息", pinyin: "xiē xi", meaning: "to rest" },
        { word: "饮茶", pinyin: "yǐn chá", meaning: "to have tea" },
        { word: "唐", pinyin: "táng", meaning: "Tang dynasty" },
        { word: "磨", pinyin: "mó", meaning: "to rub" },
        { word: "葱", pinyin: "cōng", meaning: "scallion" },
        { word: "橘子", pinyin: "jú zi", meaning: "tangerine" },
        { word: "宋", pinyin: "sòng", meaning: "Song dynasty" },
        { word: "柴", pinyin: "chái", meaning: "firewood" },
        { word: "鼎盛", pinyin: "dǐng shèng", meaning: "peak period" },
        { word: "醋", pinyin: "cù", meaning: "vinegar" },
        { word: "沸水", pinyin: "fèi shuǐ", meaning: "boiling water" },
        { word: "调匀", pinyin: "tiáo yún", meaning: "to blend/stir evenly" },
        { word: "搅拌", pinyin: "jiǎo bàn", meaning: "to stir" },
        { word: "步骤", pinyin: "bù zhòu", meaning: "procedure" },
        { word: "鉴赏", pinyin: "jiàn shǎng", meaning: "to appreciate" },
        { word: "消暑", pinyin: "xiāo shǔ", meaning: "to cool off" },
        { word: "菌", pinyin: "jūn", meaning: "bacteria/fungus" },
        { word: "舞蹈", pinyin: "wǔ dǎo", meaning: "dance" },
        { word: "节奏", pinyin: "jié zòu", meaning: "rhythm" },
        { word: "霹雳舞", pinyin: "pī lì wǔ", meaning: "breakdance" },
        { word: "肌肉", pinyin: "jī ròu", meaning: "muscle" },
        { word: "风靡", pinyin: "fēng mǐ", meaning: "fashionable" },
        { word: "热潮", pinyin: "rè cháo", meaning: "upsurge" },
        { word: "掀起", pinyin: "xiān qǐ", meaning: "to lift / set off" },
        { word: "雨后春笋", pinyin: "yǔ hòu chūn sǔn", meaning: "emerge rapidly" },
        { word: "爆发力", pinyin: "bào fā lì", meaning: "explosive power" },
        { word: "默契", pinyin: "mò qì", meaning: "tacit understanding" },
        { word: "焕发", pinyin: "huàn fā", meaning: "radiant" },
        { word: "真挚", pinyin: "zhēn zhì", meaning: "sincere" },
        { word: "名额", pinyin: "míng é", meaning: "quota" },
        { word: "链接", pinyin: "liàn jiē", meaning: "link" },
        { word: "师傅", pinyin: "shī fu", meaning: "master" },
        { word: "擅长", pinyin: "shàn cháng", meaning: "be good at" },
        { word: "裁缝", pinyin: "cái féng", meaning: "tailor" },
        { word: "编织", pinyin: "biān zhī", meaning: "to weave" },
        { word: "烘焙", pinyin: "hōng bèi", meaning: "to bake" },
        { word: "匠人", pinyin: "jiàng rén", meaning: "craftsman" },
        { word: "讲述", pinyin: "jiǎng shù", meaning: "to talk about" },
        { word: "黎明", pinyin: "lí míng", meaning: "dawn" },
        { word: "禽", pinyin: "qín", meaning: "birds and animals" },
        { word: "苏醒", pinyin: "sū xǐng", meaning: "to wake up" },
        { word: "晚霞", pinyin: "wǎn xiá", meaning: "sunset glow" },
        { word: "添砖加瓦", pinyin: "tiān zhuān jiā wǎ", meaning: "do one's bit to help" },
        { word: "唇齿相依", pinyin: "chún chǐ xiāng yī", meaning: "closely related" },
        { word: "族裔", pinyin: "zú yì", meaning: "ethnic group" },
        { word: "亲戚", pinyin: "qīn qi", meaning: "relative" },
        { word: "援助", pinyin: "yuán shǒu", meaning: "assistance" },
        { word: "侥幸", pinyin: "jiǎo xìng", meaning: "luckily" },
        { word: "慷慨解囊", pinyin: "kāng kǎi jiě náng", meaning: "contribute generously" },
        { word: "渡", pinyin: "dù", meaning: "to cross" },
        { word: "篱笆", pinyin: "lí ba", meaning: "fence" },
        { word: "心力交瘁", pinyin: "xīn lì jiāo cuì", meaning: "mentally and physically exhausted" },
        { word: "雪中送炭", pinyin: "xuě zhōng sòng tàn", meaning: "timely help" },
        { word: "恰好", pinyin: "qià hǎo", meaning: "as it turns out" },
        { word: "弥补", pinyin: "mí bǔ", meaning: "to complement" },
        { word: "谚语", pinyin: "yàn yǔ", meaning: "proverb" },
        { word: "和睦", pinyin: "hé mù", meaning: "peaceful/harmonious" },
        { word: "冷漠", pinyin: "lěng mò", meaning: "cold and indifferent" },
        { word: "挑剔", pinyin: "tiāo ti", meaning: "picky" },
        { word: "网络", pinyin: "wǎng luò", meaning: "network" },
        { word: "锯子", pinyin: "jù zi", meaning: "a saw" },
        { word: "开销", pinyin: "kāi xiāo", meaning: "expenses" },
        { word: "溜", pinyin: "liù", meaning: "to stroll" },
        { word: "栓", pinyin: "shuān", meaning: "tie / stopper" },
        { word: "渠道", pinyin: "qú dào", meaning: "channel" },
        { word: "弊端", pinyin: "bì duān", meaning: "drawback" },
        { word: "培训", pinyin: "péi xùn", meaning: "to train" },
        { word: "阐述", pinyin: "chǎn shù", meaning: "elaborate" },
        { word: "铿锵", pinyin: "kēng qiāng", meaning: "sonorous" },
        { word: "雅俗", pinyin: "yǎ sú", meaning: "elegant and popular" },
        { word: "抑扬顿挫", pinyin: "yì yáng dùn cuò", meaning: "cadence" },
        { word: "僵硬", pinyin: "jiāng yìng", meaning: "stiff" },
        { word: "言简意赅", pinyin: "yán jiǎn yǐ gāi", meaning: "concise and comprehensive" },
        { word: "啰嗦", pinyin: "luō suo", meaning: "long-winded" },
        { word: "遐想", pinyin: "xià xiǎng", meaning: "reverie" },
        { word: "枯燥", pinyin: "kū zào", meaning: "dry and dull" },
        { word: "筛选", pinyin: "shāi xuǎn", meaning: "to filter" },
        { word: "誉", pinyin: "yù", meaning: "reputation" },
        { word: "润滑剂", pinyin: "rùn huá jì", meaning: "lubricant" },
        { word: "浏览", pinyin: "liú lǎn", meaning: "to browse/skim" },
        { word: "不胜枚举", pinyin: "bú shèng méi jǔ", meaning: "too numerous to mention" },
        { word: "扼腕", pinyin: "è wàn", meaning: "wring hands in regret" },
        { word: "氛围", pinyin: "fēn wéi", meaning: "ambience" },
        { word: "体恤", pinyin: "tǐ xù", meaning: "to empathize" },
        { word: "谦虚", pinyin: "qiān xū", meaning: "modest" },
        { word: "裨益", pinyin: "bì yì", meaning: "benefit" },
        { word: "流言蜚语", pinyin: "liú yán fēi yǔ", meaning: "rumors and slanders" },
        { word: "严峻", pinyin: "yán jùn", meaning: "severe" },
        { word: "扰乱", pinyin: "rǎo luàn", meaning: "to disturb" },
        { word: "甚嚣尘上", pinyin: "shèn xiāo chén shàng", meaning: "tremendous clamor" },
        { word: "基础", pinyin: "jī chǔ", meaning: "base" },
        { word: "涵盖", pinyin: "hán gài", meaning: "to cover" },
        { word: "崛起", pinyin: "jué qǐ", meaning: "rise abruptly" },
        { word: "颠覆", pinyin: "diān fù", meaning: "subvert" },
        { word: "报刊", pinyin: "bào kān", meaning: "newspapers/magazines" },
        { word: "书籍", pinyin: "shū jí", meaning: "books" },
        { word: "传播", pinyin: "chuán bō", meaning: "disseminate" },
        { word: "舶", pinyin: "bó", meaning: "to push aside" },
        { word: "天涯", pinyin: "tiān yá", meaning: "end of the world" },
        { word: "限制", pinyin: "xiàn zhì", meaning: "restrict" },
        { word: "屏幕", pinyin: "píng mù", meaning: "screen" },
        { word: "按钮", pinyin: "àn niǔ", meaning: "push button" },
        { word: "庞大", pinyin: "páng dà", meaning: "huge" },
        { word: "疆界", pinyin: "jiāng jiè", meaning: "border" },
        { word: "阶段", pinyin: "jiē duàn", meaning: "stage" },
        { word: "同侪", pinyin: "tóng chái", meaning: "peer" },
        { word: "撰写", pinyin: "zhuàn xiě", meaning: "to write" },
        { word: "筹备", pinyin: "chóu bèi", meaning: "preparations" },
        { word: "募捐", pinyin: "mù juān", meaning: "solicit contributions" },
        { word: "实践", pinyin: "shí jiàn", meaning: "put into practice" },
        { word: "震撼", pinyin: "zhèn hàn", meaning: "shock" },
        { word: "融会贯通", pinyin: "róng huì guàn tōng", meaning: "master via comprehensive study" },
        { word: "循规蹈矩", pinyin: "xún guī dǎo jǔ", meaning: "follow rules inflexibly" },
        { word: "腼腆", pinyin: "miǎn tiǎn", meaning: "shy" },
        { word: "咨询", pinyin: "zī xún", meaning: "to consult" },
        { word: "数据", pinyin: "shù jù", meaning: "data" },
        { word: "分析", pinyin: "fēn xī", meaning: "analyze" },
        { word: "冰淇淋", pinyin: "bīng qí lín", meaning: "ice cream" },
        { word: "充实", pinyin: "chōng shí", meaning: "enrich/fulfilling" },
        { word: "雄鹰", pinyin: "xióng yīng", meaning: "male eagle" },
        { word: "渺小", pinyin: "miǎo xiǎo", meaning: "tiny" },
        { word: "坐井观天", pinyin: "zuò jǐng guān tiān", meaning: "narrow-minded" },
        { word: "自鸣得意", pinyin: "zì míng dé yì", meaning: "think highly of oneself" },
        { word: "孤陋寡闻", pinyin: "gū lòu guǎ wén", meaning: "ignorant" },
        { word: "奥妙", pinyin: "ào miào", meaning: "secret" },
        { word: "寓言", pinyin: "yù yán", meaning: "fable" },
        { word: "桨", pinyin: "jiǎng", meaning: "oar" },
        { word: "浅尝辄止", pinyin: "qiǎn cháng zhé zhǐ", meaning: "dabble and stop" },
        { word: "哲学", pinyin: "zhé xué", meaning: "philosophy" },
        { word: "比喻", pinyin: "bǐ yù", meaning: "metaphor/simile" },
        { word: "热忱", pinyin: "rè chén", meaning: "zeal" },
        { word: "清澈", pinyin: "qīng chè", meaning: "clear liquid" },
        { word: "持之以恒", pinyin: "chí zhī yǐ héng", meaning: "persevere" },
        { word: "干涸", pinyin: "gān hé", meaning: "to dry up" },
        { word: "浇灌", pinyin: "jiāo guàn", meaning: "to water" },
        { word: "落伍", pinyin: "luò wǔ", meaning: "fall behind" },
        { word: "楷模", pinyin: "kǎi mó", meaning: "model" },
        { word: "孜孜不倦", pinyin: "zī zī bú juàn", meaning: "continuous effort" },
        { word: "敷衍", pinyin: "fū yǎn", meaning: "half-heartedly" },
        { word: "逆水行舟", pinyin: "nì shuǐ xíng zhōu", meaning: "navigating against current" },
        { word: "淘汰", pinyin: "táo tài", meaning: "wash out" },
        { word: "佐证", pinyin: "zuǒ zhèng", meaning: "evidence" },
        { word: "平庸", pinyin: "píng yōng", meaning: "mediocre" },
        { word: "岂", pinyin: "qǐ", meaning: "how? (emphatic)" },
        { word: "诠释", pinyin: "quán shì", meaning: "interpret" },
        { word: "抛锚", pinyin: "pāo máo", meaning: "anchor or breakdown" },
        { word: "郁闷", pinyin: "yù mèn", meaning: "depressed/gloomy" },
        { word: "逗", pinyin: "dòu", meaning: "tease" },
        { word: "叼", pinyin: "diāo", meaning: "hold with mouth" },
        { word: "挑战", pinyin: "tiǎo zhàn", meaning: "challenge" },
        { word: "绊", pinyin: "bàn", meaning: "trip" },
        { word: "雀跃", pinyin: "què yuè", meaning: "excited" },
        { word: "攀登", pinyin: "pān dēng", meaning: "climb" },
        { word: "山脉", pinyin: "shān mài", meaning: "mountain range" },
        { word: "宇宙", pinyin: "yǔ zhòu", meaning: "universe" },
        { word: "跋涉", pinyin: "bá shè", meaning: "trek/trudge" },
        { word: "体验", pinyin: "tǐ yàn", meaning: "experience" },
        { word: "牵挂", pinyin: "qiān guà", meaning: "worry about" },
        { word: "喉咙", pinyin: "hóu lóng", meaning: "throat" },
        { word: "唤", pinyin: "huàn", meaning: "call" },
        { word: "绽放", pinyin: "zhàn fàng", meaning: "blossom" },
        { word: "绷", pinyin: "bēng", meaning: "draw tight" },
        { word: "一般", pinyin: "yì bān", meaning: "same" },
        { word: "无奈", pinyin: "wú nài", meaning: "helpless" },
        { word: "寺庙", pinyin: "sì miào", meaning: "temple" },
        { word: "幽静", pinyin: "yōu jìng", meaning: "quiet" },
        { word: "诧异", pinyin: "chà yì", meaning: "surprised" },
        { word: "贱", pinyin: "jiàn", meaning: "inexpensive" },
        { word: "哽咽", pinyin: "gěng yè", meaning: "choke with emotion" },
        { word: "眼眶", pinyin: "yǎn kuàng", meaning: "eye socket" },
        { word: "隆重", pinyin: "lóng zhòng", meaning: "grand" },
        { word: "咀嚼", pinyin: "jǔ jué", meaning: "chew" },
        { word: "诅咒", pinyin: "zǔ zhòu", meaning: "curse" },
        { word: "洋溢", pinyin: "yáng yì", meaning: "brimming with" },
        { word: "慈祥", pinyin: "cí xiáng", meaning: "kindly" },
        { word: "潭", pinyin: "tán", meaning: "deep pool" },
        { word: "教授", pinyin: "jiào shòu", meaning: "professor" },
        { word: "割舍", pinyin: "gē shě", meaning: "give up" }
    ]
};
