const vocabData = {
    "Level 1": [
        { word: "淘气", pinyin: "táo qì", meaning: "naughty; mischievous" },
        { word: "惹", pinyin: "rě", meaning: "to provoke; to attract (troubles); to cause (problems)" },
        { word: "两肋插刀", pinyin: "liǎng lèi chā dāo", meaning: "to attach great importance to friendship; sacrifice oneself" },
        { word: "赵", pinyin: "zhào", meaning: "surname Zhao" },
        { word: "科技", pinyin: "kē jì", meaning: "science and technology" },
        { word: "来者不拒", pinyin: "lái zhě bù jù", meaning: "all comers welcome" },
        { word: "小事一桩", pinyin: "xiǎo shì yī zhuāng", meaning: "a piece of cake" },
        { word: "口头禅", pinyin: "kǒu tóu chán", meaning: "catchphrase; mantra" },
        { word: "人缘", pinyin: "rén yuán", meaning: "relations with other people" },
        { word: "性格", pinyin: "xìng gé", meaning: "nature; temperament; character" },
        { word: "直率", pinyin: "zhí shuài", meaning: "candid; frank" },
        { word: "得罪", pinyin: "dé zuì", meaning: "to commit an offense; excuse me!" },
        { word: "别扭", pinyin: "biè niu", meaning: "awkward; difficult; uncomfortable" },
        { word: "争辩", pinyin: "zhēng biàn", meaning: "a dispute; to wrangle" },
        { word: "即使", pinyin: "jí shǐ", meaning: "even if; even though" },
        { word: "冤枉", pinyin: "yuān wang", meaning: "to accuse wrongly; treated unjustly" },
        { word: "推荐", pinyin: "tuī jiàn", meaning: "to recommend" },
        { word: "捣乱", pinyin: "dǎo luàn", meaning: "to disturb; look for trouble" },
        { word: "瞬间", pinyin: "shù n jiān", meaning: "in an instant" },
        { word: "粘", pinyin: "zhān", meaning: "to glue; to paste; to stick to" },
        { word: "兴致勃勃", pinyin: "xìng zhì bó bó", meaning: "in high spirits; full of zest" },
        { word: "狼狈", pinyin: "láng bèi", meaning: "in a difficult situation" },
        { word: "蛋液", pinyin: "dàn yè", meaning: "liquid of the egg" },
        { word: "讥讽", pinyin: "jī fěng", meaning: "to satirize; to ridicule" },
        { word: "赌气", pinyin: "dǔ qì", meaning: "to act in a fit of pique" },
        { word: "嚷", pinyin: "rǎng", meaning: "to shout; blurt out" },
        { word: "小心翼翼", pinyin: "xiǎo xīn yì yì", meaning: "very carefully; prudent" },
        { word: "荧光笔", pinyin: "yíng guāng bǐ", meaning: "highlighter" },
        { word: "抵挡", pinyin: "dǐ dǎng", meaning: "to resist; to ward off" },
        { word: "拉扯", pinyin: "lā che", meaning: "to drag; to pull; to raise a child" },
        { word: "手足无措", pinyin: "shǒu zú wú cuò", meaning: "at a loss to know what to do" },
        { word: "审案", pinyin: "shěn àn", meaning: "try a case" },
        { word: "律师", pinyin: "lǜ shī", meaning: "lawyer" },
        { word: "振振有词", pinyin: "zhèn zhèn yǒu cí", meaning: "to argue with courage of one's convictions" },
        { word: "心虚", pinyin: "xīn xū", meaning: "guilty conscience" },
        { word: "哑口无言", pinyin: "yǎ kǒu wú yán", meaning: "left speechless" },
        { word: "判决", pinyin: "pàn jué", meaning: "judgment; sentence" },
        { word: "泄", pinyin: "xiè", meaning: "to leak; to divulge; to give vent" },
        { word: "葡萄", pinyin: "pú tao", meaning: "grape" },
        { word: "风俗", pinyin: "fēng sú", meaning: "social custom" },
        { word: "象征", pinyin: "xiàng zhēng", meaning: "emblem; symbol" },
        { word: "辞旧迎新", pinyin: "cí jiù yíng xīn", meaning: "ring out the old and ring in the new" },
        { word: "燃放", pinyin: "rán fàng", meaning: "to light; set off" },
        { word: "厄运", pinyin: "è yùn", meaning: "bad luck; misfortune" },
        { word: "瓶瓶罐罐", pinyin: "píng píng guàn guàn", meaning: "bottles and cans" },
        { word: "前夕", pinyin: "qián xī", meaning: "eve" },
        { word: "碗碟", pinyin: "wǎn dié", meaning: "bowls and plates" },
        { word: "预示", pinyin: "yù shì", meaning: "to indicate; to foretell" },
        { word: "忙碌", pinyin: "máng lù", meaning: "busy; bustling" },
        { word: "兆头", pinyin: "zhào tou", meaning: "omen; sign" },
        { word: "遥远", pinyin: "yáo yuǎn", meaning: "distant; remote" },
        { word: "恭敬", pinyin: "gōng jìng", meaning: "deferential; respectful" },
        { word: "万事大吉", pinyin: "wàn shì dà jí", meaning: "all is well" },
        { word: "元旦", pinyin: "yuán dàn", meaning: "New Year's Day" },
        { word: "贼", pinyin: "zéi", meaning: "thief" },
        { word: "鱼尾纹", pinyin: "yú wěi wén", meaning: "crow's feet" },
        { word: "装饰", pinyin: "zhuāng shì", meaning: "to decorate" },
        { word: "圣诞", pinyin: "shèng dàn", meaning: "Christmas" },
        { word: "格格不入", pinyin: "gé gé bù rù", meaning: "inharmonious; incompatible" },
        { word: "结婚", pinyin: "jié hūn", meaning: "to marry" },
        { word: "嫁", pinyin: "jià", meaning: "to marry (of a woman)" },
        { word: "视讯", pinyin: "shì xùn", meaning: "video call" },
        { word: "沉默寡言", pinyin: "chén mò guǎ yán", meaning: "reticent; silent" },
        { word: "酷", pinyin: "kù", meaning: "cool" },
        { word: "副", pinyin: "fù", meaning: "classifier for facial expressions" },
        { word: "承诺", pinyin: "chéng nuò", meaning: "to promise" },
        { word: "歉意", pinyin: "qiàn yì", meaning: "apology; regret" },
        { word: "蒸腾", pinyin: "zhēng téng", meaning: "to rise (of vapor)" },
        { word: "围炉", pinyin: "wéi lú", meaning: "steamboat" },
        { word: "叽叽喳喳", pinyin: "jī jī zhā zhā", meaning: "chirp; chatter" },
        { word: "缺席", pinyin: "quē xí", meaning: "absence; absent" },
        { word: "悦耳", pinyin: "yuè ěr", meaning: "sweet-sounding" },
        { word: "红枣", pinyin: "hóng zǎo", meaning: "red date" },
        { word: "儿媳妇", pinyin: "ér xí fu", meaning: "daughter-in-law" },
        { word: "莫名其妙", pinyin: "mò míng qí miào", meaning: "inexplicable; baffling" },
        { word: "疑惑", pinyin: "yí huò", meaning: "suspicion; to puzzle over" },
        { word: "魅力", pinyin: "mèi lì", meaning: "charm; charisma" },
        { word: "博物馆", pinyin: "bó wù guǎn", meaning: "museum" },
        { word: "悠久", pinyin: "yōu jiǔ", meaning: "long (history/tradition)" },
        { word: "遗产", pinyin: "yí chǎn", meaning: "heritage; legacy" },
        { word: "巴刹", pinyin: "bā shā", meaning: "wet market" },
        { word: "同胞", pinyin: "tóng bāo", meaning: "fellow citizen; compatriot" },
        { word: "融合", pinyin: "róng hé", meaning: "mixture; fusion; harmonize" },
        { word: "城堡", pinyin: "chéng bǎo", meaning: "castle" },
        { word: "皇宫", pinyin: "huáng gōng", meaning: "imperial palace" },
        { word: "时尚", pinyin: "shí shàng", meaning: "fashion" },
        { word: "流连忘返", pinyin: "liú lián wàng fǎn", meaning: "linger and forget to go home" },
        { word: "彩绘", pinyin: "cǎi huì", meaning: "painted-on designs" },
        { word: "娱乐", pinyin: "yú lè", meaning: "entertainment" },
        { word: "探索", pinyin: "tàn suǒ", meaning: "to explore" },
        { word: "娘惹", pinyin: "niáng rě", meaning: "Nyonya" },
        { word: "拍摄", pinyin: "pāi shè", meaning: "to film; shoot" },
        { word: "平均", pinyin: "píng jūn", meaning: "average" },
        { word: "繁忙", pinyin: "fán máng", meaning: "busy; bustling" },
        { word: "闪耀", pinyin: "shǎn yào", meaning: "glitter; sparkle" },
        { word: "衡量", pinyin: "héng liáng", meaning: "measure; weigh" },
        { word: "覆盖", pinyin: "fù gài", meaning: "to cover" },
        { word: "玻璃", pinyin: "bō li", meaning: "glass" },
        { word: "瀑布", pinyin: "pù bù", meaning: "waterfall" },
        { word: "循环", pinyin: "xún huán", meaning: "cycle; circulate" },
        { word: "谷", pinyin: "gǔ", meaning: "valley; grain" },
        { word: "株", pinyin: "zhū", meaning: "a plant; strain" },
        { word: "设施", pinyin: "shè shī", meaning: "facilities" },
        { word: "蹦跳", pinyin: "bèng tiào", meaning: "to hop; jump" },
        { word: "甚至", pinyin: "shèn zhì", meaning: "even" },
        { word: "投降", pinyin: "tóu xiáng", meaning: "surrender" },
        { word: "自治", pinyin: "zì zhì", meaning: "autonomy" },
        { word: "棕色", pinyin: "zōng sè", meaning: "brown" },
        { word: "栏", pinyin: "lán", meaning: "fence; railing" },
        { word: "氧化", pinyin: "yǎng huà", meaning: "oxidize" },
        { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
        { word: "属于", pinyin: "shǔ yú", meaning: "belong to" },
        { word: "宁静", pinyin: "níng jìng", meaning: "tranquil" },
        { word: "坚持不懈", pinyin: "jiān chí bù xiè", meaning: "persevere unremittingly" },
        { word: "以礼待人", pinyin: "yǐ lǐ dài rén", meaning: "treat with courtesy" },
        { word: "开卷有益", pinyin: "kāi juàn yǒu yì", meaning: "reading is beneficial" },
        { word: "新颖", pinyin: "xīn yǐng", meaning: "new and original" },
        { word: "戏剧", pinyin: "xì jù", meaning: "drama" },
        { word: "工作坊", pinyin: "gōng zuò fāng", meaning: "workshop" },
        { word: "尴尬", pinyin: "gān gà", meaning: "awkward; embarrassed" },
        { word: "维护", pinyin: "wéi hù", meaning: "safeguard; maintain" },
        { word: "一帆风顺", pinyin: "yī fān fēng shùn", meaning: "smooth sailing" },
        { word: "友谊", pinyin: "yǒu yì", meaning: "friendship" },
        { word: "有效", pinyin: "yǒu xiào", meaning: "effective; valid" },
        { word: "策略", pinyin: "cè lüè", meaning: "strategy" },
        { word: "辅导员", pinyin: "fǔ dǎo yuán", meaning: "counsellor" },
        { word: "嘉宾", pinyin: "jiā bīn", meaning: "esteemed guest" },
        { word: "赖床", pinyin: "lài chuáng", meaning: "dawdle in bed" },
        { word: "催促", pinyin: "cuī cù", meaning: "to urge" },
        { word: "滋味", pinyin: "zī wèi", meaning: "taste; flavor; feeling" },
        { word: "哀求", pinyin: "āi qiú", meaning: "to plead" },
        { word: "硬着头皮", pinyin: "yìng zhe tou pí", meaning: "brace oneself to do something" },
        { word: "抡", pinyin: "lūn", meaning: "to swing; wave" },
        { word: "藤鞭", pinyin: "téng biān", meaning: "rattan cane" },
        { word: "挨打", pinyin: "ái dǎ", meaning: "take a beating" },
        { word: "女佣", pinyin: "nǚ yōng", meaning: "maid" },
        { word: "雨篷", pinyin: "yǔ péng", meaning: "rain cover" },
        { word: "泪痕", pinyin: "lèi hén", meaning: "tear stains" },
        { word: "早晨", pinyin: "zǎo chén", meaning: "early morning" },
        { word: "猛", pinyin: "měng", meaning: "fierce; sudden" },
        { word: "嗓子眼", pinyin: "sǎng zi yǎn", meaning: "throat" },
        { word: "允许", pinyin: "yǔ nǔ", meaning: "permit; allow" },
        { word: "讲究", pinyin: "jiǎng jiu", meaning: "pay attention to quality" },
        { word: "相貌", pinyin: "xiàng mào", meaning: "appearance" },
        { word: "何必", pinyin: "hé bì", meaning: "why should; no need" },
        { word: "记账", pinyin: "jì zhàng", meaning: "bookkeeping" },
        { word: "亏", pinyin: "kuī", meaning: "deficit; deficiency" },
        { word: "撇", pinyin: "piē", meaning: "cast away" },
        { word: "慢条斯理", pinyin: "màn tiáo sī lǐ", meaning: "unhurried; leisurely" },
        { word: "起航", pinyin: "qǐ háng", meaning: "set sail / take off" },
        { word: "焦急", pinyin: "jiāo jí", meaning: "anxiety; anxious" },
        { word: "剩", pinyin: "shèng", meaning: "remain; left" },
        { word: "牙膏", pinyin: "yá gāo", meaning: "toothpaste" },
        { word: "橡皮擦", pinyin: "xiàng pí cā", meaning: "eraser" },
        { word: "薯条", pinyin: "shǔ tiáo", meaning: "french fries" },
        { word: "番茄酱", pinyin: "fān qié jiàng", meaning: "ketchup" },
        { word: "偶尔", pinyin: "ǒu ěr", meaning: "occasionally" },
        { word: "评委", pinyin: "píng wěi", meaning: "judging panel" },
        { word: "晋级", pinyin: "jìn jí", meaning: "promotion; advance" },
        { word: "奖励", pinyin: "jiǎng lì", meaning: "reward" },
        { word: "获得", pinyin: "huò dé", meaning: "obtain; receive" },
        { word: "企业", pinyin: "qǐ yè", meaning: "enterprise; company" },
        { word: "牧场", pinyin: "mù chǎng", meaning: "pasture; ranch" },
        { word: "艘", pinyin: "sōu", meaning: "classifier for ships" },
        { word: "潜水", pinyin: "qián shuǐ", meaning: "to dive" },
        { word: "屁股", pinyin: "pì gǔ", meaning: "buttocks" },
        { word: "翘", pinyin: "qiào", meaning: "stick up; tilt" },
        { word: "仿佛", pinyin: "fǎng fú", meaning: "seem; as if" },
        { word: "潜水艇", pinyin: "qián shuǐ tǐng", meaning: "submarine" },
        { word: "确切", pinyin: "què qiè", meaning: "exact; definite" },
        { word: "浑身", pinyin: "hún shēn", meaning: "all over the body" },
        { word: "基因", pinyin: "jī yīn", meaning: "gene" },
        { word: "一哄而散", pinyin: "yī hòng ér sàn", meaning: "disperse in confusion" },
        { word: "颁布", pinyin: "bān bù", meaning: "issue; enact" },
        { word: "手势", pinyin: "shǒu shì", meaning: "gesture" },
        { word: "泛", pinyin: "fàn", meaning: "float; suffused" },
        { word: "泡沫", pinyin: "pào mò", meaning: "foam; bubble" },
        { word: "伤脑筋", pinyin: "shāng nǎo jīn", meaning: "real headache" },
        { word: "拜访", pinyin: "bài fǎng", meaning: "to visit" },
        { word: "漫步", pinyin: "màn bù", meaning: "wander; ramble" },
        { word: "中央", pinyin: "zhōng yāng", meaning: "central" },
        { word: "绞尽脑汁", pinyin: "jiǎo jìn nǎo zhī", meaning: "rack one's brains" },
        { word: "银行", pinyin: "yín háng", meaning: "bank" },
        { word: "华侨", pinyin: "huá qiáo", meaning: "overseas Chinese" },
        { word: "由衷", pinyin: "yóu zhōng", meaning: "heartfelt; sincere" },
        { word: "摩天大楼", pinyin: "mó tiān dà lóu", meaning: "skyscraper" },
        { word: "抨击", pinyin: "pēng jī", meaning: "attack (verbally)" },
        { word: "薄薄的", pinyin: "báo báo de", meaning: "thin" },
        { word: "挫折", pinyin: "cuò zhé", meaning: "setback" },
        { word: "油漆", pinyin: "yóu qī", meaning: "paint; lacquer" },
        { word: "栏杆", pinyin: "lán gān", meaning: "railing" },
        { word: "宿舍", pinyin: "sù shè", meaning: "dormitory" },
        { word: "凭", pinyin: "píng", meaning: "rely on" },
        { word: "订购", pinyin: "dìng gòu", meaning: "place an order" },
        { word: "欣慰", pinyin: "xīn wèi", meaning: "gratified" },
        { word: "塔台", pinyin: "tǎ tái", meaning: "control tower" },
        { word: "范围", pinyin: "fàn wéi", meaning: "range; scope" },
        { word: "特殊", pinyin: "tè shū", meaning: "special" },
        { word: "警惕", pinyin: "jǐng tì", meaning: "vigilant; alert" },
        { word: "失误", pinyin: "shī wù", meaning: "mistake" },
        { word: "不堪设想", pinyin: "bù kān shè xiǎng", meaning: "too horrible to contemplate" },
        { word: "脂肪", pinyin: "zhī fáng", meaning: "fat" },
        { word: "截至", pinyin: "jié zhì", meaning: "up to (a time)" },
        { word: "行驶", pinyin: "xíng shǐ", meaning: "travel (vehicle)" },
        { word: "延误", pinyin: "yán wu", meaning: "delay" },
        { word: "稳定", pinyin: "wěn dìng", meaning: "steady; stable" },
        { word: "幕后", pinyin: "mù hòu", meaning: "behind the scenes" },
        { word: "贡献", pinyin: "gòng xiàn", meaning: "contribute" },
        { word: "明知山有虎", pinyin: "míng zhī shān yǒu hǔ", meaning: "taking risks despite danger" },
        { word: "漏夜", pinyin: "lòu yè", meaning: "late at night" },
        { word: "轨道", pinyin: "guǐ dào", meaning: "track; orbit" },
        { word: "就绪", pinyin: "jiù xù", meaning: "ready; in order" },
        { word: "凌晨", pinyin: "líng chén", meaning: "early morning" },
        { word: "隧道", pinyin: "suì dào", meaning: "tunnel" },
        { word: "裂痕", pinyin: "liè hén", meaning: "crack; split" },
        { word: "扫描", pinyin: "sǎo miáo", meaning: "scan" },
        { word: "顺畅", pinyin: "shù n chàng", meaning: "fluent; smooth" },
        { word: "职业", pinyin: "zhí yè", meaning: "occupation; profession" },
        { word: "全力以赴", pinyin: "quán lì yǐ fù", meaning: "all-out effort" },
        { word: "故障", pinyin: "gù zhàng", meaning: "malfunction; fault" },
        { word: "岗位", pinyin: "gǎng wèi", meaning: "a post; job" },
        { word: "芝麻", pinyin: "zhī ma", meaning: "sesame" },
        { word: "新谣", pinyin: "xīn yáo", meaning: "Singapore Chinese songs" },
        { word: "朗朗上口", pinyin: "lǎng lǎng shàng kǒu", meaning: "catchy; easy to recite" },
        { word: "奉献", pinyin: "fèng xiàn", meaning: "dedicate; devote" },
        { word: "繁荣", pinyin: "fán róng", meaning: "prosperous" },
        { word: "平凡", pinyin: "píng fán", meaning: "ordinary" },
        { word: "光芒", pinyin: "guāng máng", meaning: "rays of light" },
        { word: "有福同享", pinyin: "yǒu fú tóng xiǎng", meaning: "to share blessings together" },
{ word: "有难同当", pinyin: "yǒu nàn tóng dāng", meaning: "to face difficulties together" },
{ word: "助人为快乐之本", pinyin: "zhù rén wéi kuài lè zhī běn", meaning: "helping others is the source of happiness" },
{ word: "健将", pinyin: "jiàn jiàng", meaning: "expert; good athlete" },
{ word: "内向", pinyin: "nèi xiàng", meaning: "introverted" },
{ word: "系列", pinyin: "xì liè", meaning: "series" },
{ word: "布置", pinyin: "bù zhì", meaning: "to arrange; to assign" },
{ word: "体会", pinyin: "tǐ huì", meaning: "to experience; understanding" },
{ word: "服气", pinyin: "fú qì", meaning: "to be convinced; to accept" },
{ word: "证明", pinyin: "zhèng míng", meaning: "to prove; proof" },
{ word: "居然", pinyin: "jū rán", meaning: "unexpectedly; actually" },
{ word: "恨不得", pinyin: "hèn bu de", meaning: "to wish one could" },
{ word: "既然", pinyin: "jì rán", meaning: "since; given that" },
{ word: "辩护", pinyin: "biàn hù", meaning: "to defend; to plead" },
{ word: "报复", pinyin: "bào fù", meaning: "to retaliate; revenge" },
{ word: "错误", pinyin: "cuò wù", meaning: "mistake; error" },
{ word: "闹别扭", pinyin: "nào biè niu", meaning: "to be at odds; to have a disagreement" },
{ word: "吞吞吐吐", pinyin: "tūn tūn tǔ tǔ", meaning: "to hem and haw; hesitant in speech" },
{ word: "大吉大利", pinyin: "dà jí dà lì", meaning: "great luck and great prosperity" },
{ word: "文明", pinyin: "wén míng", meaning: "civilized; civilization" },
{ word: "品尝", pinyin: "pǐn cháng", meaning: "to taste; to sample" },
{ word: "安详", pinyin: "ān xiáng", meaning: "peaceful; serene" },
{ word: "休闲", pinyin: "xiū xián", meaning: "leisure; relaxation" },
{ word: "主题", pinyin: "zhǔ tí", meaning: "theme; topic" },
{ word: "别具一格", pinyin: "bié jù yī gé", meaning: "having a unique style" },
{ word: "面积", pinyin: "miàn jī", meaning: "area" },
{ word: "天花板", pinyin: "tiān huā bǎn", meaning: "ceiling" },
{ word: "一诺千金", pinyin: "yī nuò qiān jīn", meaning: "a promise worth a thousand pieces of gold; trustworthy" },
{ word: "言出必行", pinyin: "yán chū bì xíng", meaning: "to keep one's word" },
{ word: "起码", pinyin: "qǐ mǎ", meaning: "at least; minimum" },
{ word: "毛病", pinyin: "máo bìng", meaning: "fault; problem; bad habit" },
{ word: "不得了", pinyin: "bù dé liǎo", meaning: "extremely; terrible; amazing" },
{ word: "情愿", pinyin: "qíng yuàn", meaning: "to prefer; be willing" },
{ word: "缘故", pinyin: "yuán gù", meaning: "reason; cause" },
{ word: "记性", pinyin: "jì xing", meaning: "memory" },
{ word: "精明", pinyin: "jīng míng", meaning: "shrewd; smart" },
{ word: "创新", pinyin: "chuàng xīn", meaning: "innovation; to innovate" },
{ word: "腾空而起", pinyin: "téng kōng ér qǐ", meaning: "to rise into the air" },
{ word: "降落", pinyin: "jiàng luò", meaning: "to land; to descend" },
{ word: "打量", pinyin: "dǎ liang", meaning: "to size up; to look over" },
{ word: "打交道", pinyin: "dǎ jiāo dào", meaning: "to deal with; to interact with" },
{ word: "而已", pinyin: "ér yǐ", meaning: "that's all; merely" },
{ word: "及时", pinyin: "jí shí", meaning: "timely; in time" },
{ word: "一旦", pinyin: "yī dàn", meaning: "once; in case" },
{ word: "心满意足", pinyin: "xīn mǎn yì zú", meaning: "perfectly contented; satisfied" },
{ word: "维修", pinyin: "wéi xiū", meaning: "maintenance; repair" },
{ word: "确保", pinyin: "què bǎo", meaning: "to ensure; to guarantee" },
{ word: "投入", pinyin: "tóu rù", meaning: "to invest; to put into; devoted" },
{ word: "默默无闻", pinyin: "mò mò wú wén", meaning: "unknown; obscure; quietly working without fame" },
{ word: "微不足道", pinyin: "wēi bù zú dào", meaning: "insignificant; not worth mentioning" },
{ word: "敬业乐业", pinyin: "jìng yè lè yè", meaning: "to respect and enjoy one's work" }
    ],
    
    "Level 2": [
        { word: "犹豫", pinyin: "yóu yù", meaning: "to hesitate" },
        { word: "不分青红皂白", pinyin: "bù fēn qīng hóng zào bái", meaning: "not to distinguish between right and wrong" },
        { word: "教训", pinyin: "jiāo xun", meaning: "lesson; to lecture somebody" },
        { word: "叛逆", pinyin: "pàn nì", meaning: "to rebel; a rebel" },
        { word: "委屈", pinyin: "wěi qu", meaning: "to feel wronged; grievance" },
        { word: "内疚", pinyin: "nèi jiù", meaning: "guilty conscience; feel guilt" },
        { word: "不妨", pinyin: "bù fáng", meaning: "might as well" },
        { word: "匿名", pinyin: "nì míng", meaning: "anonymous" },
        { word: "监督", pinyin: "jiān dū", meaning: "to supervise; control" },
        { word: "代沟", pinyin: "dài gōu", meaning: "generation gap" },
        { word: "疏远", pinyin: "shū yuǎn", meaning: "to drift apart; estranged" },
        { word: "上瘾", pinyin: "shàng yǐn", meaning: "to become addicted" },
        { word: "崇拜", pinyin: "chóng bài", meaning: "to worship; adoration" },
        { word: "碰钉子", pinyin: "pèng dīng zi", meaning: "to meet with a rebuff" },
        { word: "抽屉", pinyin: "chōu ti", meaning: "drawer" },
        { word: "掀", pinyin: "xiān", meaning: "to lift; to raise" },
        { word: "写稿", pinyin: "xiě gǎo", meaning: "to write an article" },
        { word: "搜查", pinyin: "sōu chá", meaning: "to search; ransack" },
        { word: "愤怒", pinyin: "fèn nù", meaning: "angry; indignant" },
        { word: "抗议", pinyin: "kàng yì", meaning: "to protest" },
        { word: "约束", pinyin: "yuē shù", meaning: "to restrict; constrain" },
        { word: "尊重", pinyin: "zūn zhòng", meaning: "to respect" },
        { word: "吵架", pinyin: "chǎo jià", meaning: "to quarrel" },
        { word: "酸", pinyin: "suān", meaning: "sour; tart" },
        { word: "催", pinyin: "cuī", meaning: "to urge; to prompt" },
        { word: "干脆", pinyin: "gān cuì", meaning: "straightforward; clear-cut" },
        { word: "承认", pinyin: "chéng rèn", meaning: "to admit" },
        { word: "具体", pinyin: "jù tǐ", meaning: "concrete; specific" },
        { word: "何况", pinyin: "hé kuàng", meaning: "much less; let alone" },
        { word: "歉意", pinyin: "qiàn yì", meaning: "apology; regret" },
        { word: "激动", pinyin: "jī dòng", meaning: "moved emotionally; excited" },
        { word: "增进", pinyin: "zēng jìn", meaning: "to promote; enhance" },
        { word: "踏", pinyin: "tà", meaning: "to tread; stamp" },
        { word: "糟糕", pinyin: "zāo gāo", meaning: "too bad; terrible" },
        { word: "诺言", pinyin: "nuò yán", meaning: "promise" },
        { word: "实现", pinyin: "shí xiàn", meaning: "to achieve; implement" },
        { word: "仿佛", pinyin: "fǎng fú", meaning: "to seem; as if" },
        { word: "暂时", pinyin: "zàn shí", meaning: "temporary" },
        { word: "普遍", pinyin: "pǔ biàn", meaning: "universal; general" },
        { word: "代替", pinyin: "dài tì", meaning: "to replace" },
        { word: "扩大", pinyin: "kuò dà", meaning: "to expand" },
        { word: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
        { word: "劝慰", pinyin: "quàn wèi", meaning: "to console; soothe" },
        { word: "掏", pinyin: "tāo", meaning: "to fish out (from pocket)" },
        { word: "残酷", pinyin: "cán kù", meaning: "cruel" },
        { word: "观察", pinyin: "guān chá", meaning: "to observe" },
        { word: "对应", pinyin: "duì yìng", meaning: "to correspond" },
        { word: "丰富", pinyin: "fēng fù", meaning: "rich; plentiful" },
        { word: "查询", pinyin: "chá xún", meaning: "to inquire about" },
        { word: "若干", pinyin: "ruò gān", meaning: "a certain number" },
        { word: "跟踪", pinyin: "gēn zōng", meaning: "to follow; tail" },
        { word: "输入", pinyin: "shū rù", meaning: "to input" },
        { word: "点击", pinyin: "diǎn jī", meaning: "to click" },
        { word: "联系", pinyin: "lián xì", meaning: "connection; contact" },
        { word: "功能", pinyin: "gōng néng", meaning: "function; capability" },
        { word: "淙淙", pinyin: "cóng cóng", meaning: "gurgling" },
        { word: "幢", pinyin: "zhuàng", meaning: "classifier for buildings" },
        { word: "榕树", pinyin: "róng shù", meaning: "banyan tree" },
        { word: "茂密", pinyin: "mào mì", meaning: "dense; lush" },
        { word: "延伸", pinyin: "yán shēn", meaning: "to extend" },
        { word: "翠绿", pinyin: "cuì lǜ", meaning: "jade green" },
        { word: "扁", pinyin: "biǎn", meaning: "flat" },
        { word: "记录", pinyin: "jì lù", meaning: "to record" },
        { word: "隐藏", pinyin: "yǐ n cáng", meaning: "to hide; conceal" },
        { word: "我行我素", pinyin: "wǒ xíng wǒ sù", meaning: "to continue in one's own way" },
        { word: "效果", pinyin: "xiào guǒ", meaning: "result; effect" },
        { word: "非凡", pinyin: "fēi fán", meaning: "extraordinary" },
        { word: "堪称", pinyin: "kān chēng", meaning: "can be rated as" },
        { word: "抚摸", pinyin: "fǔ mō", meaning: "to caress; stroke" },
        { word: "感叹", pinyin: "gǎn tàn", meaning: "to sigh with feeling" },
        { word: "雄伟", pinyin: "xióng wěi", meaning: "grand; imposing" },
        { word: "尤其", pinyin: "yóu qí", meaning: "especially" },
        { word: "巧妙", pinyin: "qiǎo miào", meaning: "ingenious; clever" },
        { word: "独一无二", pinyin: "dú yī wú èr", meaning: "unique and unmatched" },
        { word: "闻名", pinyin: "wén míng", meaning: "famous" },
        { word: "栽种", pinyin: "zāi zhòng", meaning: "to plant" },
        { word: "排列", pinyin: "pái liè", meaning: "to arrange" },
        { word: "欣赏", pinyin: "xīn shǎng", meaning: "to appreciate" },
        { word: "赞叹", pinyin: "zàn tàn", meaning: "praise; gasp in admiration" },
        { word: "奇迹", pinyin: "qí jì", meaning: "miracle" },
        { word: "心旷神怡", pinyin: "xīn kuàng shén yí", meaning: "carefree and happy" },
        { word: "粗糙", pinyin: "cū cāo", meaning: "coarse; rough" },
        { word: "威武", pinyin: "wēi wǔ", meaning: "powerful; mighty" },
        { word: "丘陵", pinyin: "qiū líng", meaning: "hills" },
        { word: "挺拔", pinyin: "tǐng bá", meaning: "tall and straight" },
        { word: "慷慨", pinyin: "kāng kǎi", meaning: "generous" },
        { word: "窝", pinyin: "wō", meaning: "nest" },
        { word: "幽默", pinyin: "yōu mò", meaning: "humorous" },
        { word: "奇特", pinyin: "qí tè", meaning: "peculiar; odd" },
        { word: "闪烁", pinyin: "shǎn shuò", meaning: "twinkle; flicker" },
        { word: "造型", pinyin: "zào xíng", meaning: "modeling; design" },
        { word: "启发", pinyin: "qǐ fā", meaning: "to enlighten; inspire" },
        { word: "不仅", pinyin: "bù jǐn", meaning: "not only" },
        { word: "生活", pinyin: "shēng huó", meaning: "life; activity" },
        { word: "奋斗", pinyin: "fèn dòu", meaning: "strive; struggle" },
        { word: "含义", pinyin: "hán yì", meaning: "meaning; implication" },
        { word: "蒸", pinyin: "zhēng", meaning: "to steam; evaporate" },
        { word: "世纪", pinyin: "shì jì", meaning: "century" },
        { word: "寸", pinyin: "cùn", meaning: "inch" },
        { word: "刺激", pinyin: "cì jī", meaning: "to provoke; irritate" },
        { word: "概念", pinyin: "gài niàn", meaning: "concept; idea" },
        { word: "怀念", pinyin: "huái niàn", meaning: "to cherish memory" },
        { word: "热忱", pinyin: "rè chén", meaning: "zeal; enthusiasm" },
        { word: "形容", pinyin: "xíng róng", meaning: "to describe" },
        { word: "散发", pinyin: "sàn fā", meaning: "to emit; distribute" },
        { word: "气息", pinyin: "qì xī", meaning: "scent; breath" },
        { word: "浓郁", pinyin: "nóng yù", meaning: "rich; strong scent" },
        { word: "抒发", pinyin: "shū fā", meaning: "to express (emotion)" },
        { word: "振奋", pinyin: "zhèn fèn", meaning: "raise spirits" },
        { word: "昂首", pinyin: "áng shǒu", meaning: "hold head high" },
        { word: "挺胸", pinyin: "tǐng xiōng", meaning: "throw out chest" },
        { word: "辉煌", pinyin: "huī huáng", meaning: "splendid; glorious" },
        { word: "告诫", pinyin: "gào jiè", meaning: "to warn" },
        { word: "勉励", pinyin: "miǎn lì", meaning: "to encourage" },
        { word: "茁壮", pinyin: "zhuó zhuàng", meaning: "healthy and strong" },
        { word: "婆娑", pinyin: "pó suō", meaning: "to dance; whirl" },
        { word: "婀娜多姿", pinyin: "ē nuó duō zī", meaning: "graceful; elegant" },
        { word: "饱经风霜", pinyin: "bǎo jīng fēng shuāng", meaning: "weather-beaten" },
        { word: "移民", pinyin: "yí mín", meaning: "immigrate" },
        { word: "衰老", pinyin: "shuāi lǎo", meaning: "to age" },
        { word: "兴盛", pinyin: "xīng shèng", meaning: "flourish; thrive" },
        { word: "体谅", pinyin: "tǐ liàng", meaning: "to show consideration; to empathize" },
{ word: "无可厚非", pinyin: "wú kě hòu fēi", meaning: "not much to be blamed; understandable" },
{ word: "打理", pinyin: "dǎ lǐ", meaning: "to take care of; to manage" },
{ word: "家务", pinyin: "jiā wù", meaning: "housework" },
{ word: "推出", pinyin: "tuī chū", meaning: "to launch; to introduce" },
{ word: "亲切", pinyin: "qīn qiè", meaning: "kind; friendly" },
{ word: "大摇大摆", pinyin: "dà yáo dà bǎi", meaning: "swagger; strut arrogantly" },
{ word: "凶猛", pinyin: "xiōng měng", meaning: "fierce; violent" },
{ word: "活泼", pinyin: "huó pō", meaning: "lively; active" },
{ word: "媒体", pinyin: "méi tǐ", meaning: "media" },
{ word: "塑料", pinyin: "sù liào", meaning: "plastic" },
{ word: "吨", pinyin: "dūn", meaning: "ton" },
{ word: "廉价", pinyin: "lián jià", meaning: "cheap; inexpensive" },
{ word: "提供", pinyin: "tí gōng", meaning: "to provide" },
{ word: "铺", pinyin: "pū", meaning: "to spread; to lay" },
{ word: "污染", pinyin: "wū rǎn", meaning: "pollution; to pollute" },
{ word: "焚烧", pinyin: "fén shāo", meaning: "to burn; incinerate" },
{ word: "烟尘", pinyin: "yān chén", meaning: "smoke and dust" },
{ word: "土壤", pinyin: "tǔ rǎng", meaning: "soil" },
{ word: "遏制", pinyin: "è zhì", meaning: "to curb; to contain" },
{ word: "倡导", pinyin: "chàng dǎo", meaning: "to advocate" },
{ word: "逐渐", pinyin: "zhú jiàn", meaning: "gradually" },
{ word: "威胁", pinyin: "wēi xié", meaning: "threat" },
{ word: "煞费苦心", pinyin: "shà fèi kǔ xīn", meaning: "to take great pains" },
{ word: "憋", pinyin: "biē", meaning: "to hold in; to suppress" },
{ word: "委婉", pinyin: "wěi wǎn", meaning: "tactful; indirect" },
{ word: "彻底", pinyin: "chè dǐ", meaning: "thorough; complete" },
{ word: "缝", pinyin: "fèng", meaning: "seam; to sew" },
{ word: "掩", pinyin: "yǎn", meaning: "to cover; to hide" },
{ word: "恐惧", pinyin: "kǒng jù", meaning: "fear; terror" },
{ word: "走廊", pinyin: "zǒu láng", meaning: "corridor" },
{ word: "锁", pinyin: "suǒ", meaning: "lock" },
{ word: "熄灯", pinyin: "xī dēng", meaning: "lights out" },
{ word: "颤抖", pinyin: "chàn dǒu", meaning: "to tremble" },
{ word: "隐约", pinyin: "yǐn yuē", meaning: "faint; indistinct" },
{ word: "瑟瑟", pinyin: "sè sè", meaning: "shivering sound; trembling" },
{ word: "恐怖", pinyin: "kǒng bù", meaning: "horrible; terrifying" },
{ word: "通宵", pinyin: "tōng xiāo", meaning: "all night; overnight" },
{ word: "惊悚", pinyin: "jīng sǒng", meaning: "thrilling; terrifying" },
{ word: "和谐", pinyin: "hé xié", meaning: "harmonious" },
{ word: "冤家", pinyin: "yuān jiā", meaning: "enemy; ill-fated pair" },
{ word: "误会", pinyin: "wù huì", meaning: "misunderstanding" },
{ word: "脖子", pinyin: "bó zi", meaning: "neck" },
{ word: "社交媒体", pinyin: "shè jiāo méi tǐ", meaning: "social media" },
{ word: "缺陷", pinyin: "quē xiàn", meaning: "defect; flaw" },
{ word: "姿势", pinyin: "zī shì", meaning: "posture; position" },
{ word: "拘束", pinyin: "jū shù", meaning: "restrained; constrained" },
{ word: "嘈杂", pinyin: "cáo zá", meaning: "noisy; chaotic" },
{ word: "沮丧", pinyin: "jǔ sàng", meaning: "depressed; frustrated" },
{ word: "若有所思", pinyin: "ruò yǒu suǒ sī", meaning: "lost in thought" },
{ word: "模糊", pinyin: "mó hu", meaning: "blurred; vague" },
{ word: "敏感", pinyin: "mǐn gǎn", meaning: "sensitive" },
{ word: "掩饰", pinyin: "yǎn shì", meaning: "to conceal; to cover up" },
{ word: "摄影", pinyin: "shè yǐng", meaning: "photography" },
{ word: "谷底", pinyin: "gǔ dǐ", meaning: "valley bottom; lowest point" },
{ word: "姿态", pinyin: "zī tài", meaning: "posture; attitude" },
{ word: "接触", pinyin: "jiē chù", meaning: "to contact; to touch" },
{ word: "合拢", pinyin: "hé lǒng", meaning: "to close; to fold together" },
{ word: "林荫", pinyin: "lín yīn", meaning: "shade of trees" },
{ word: "樟宜", pinyin: "zhāng yí", meaning: "Changi (place name)" },
{ word: "耸立", pinyin: "sǒng lì", meaning: "to tower; to stand tall" },
{ word: "温馨", pinyin: "wēn xīn", meaning: "warm; cozy" },
{ word: "撑", pinyin: "chēng", meaning: "to support; to hold up" },
{ word: "同甘共苦", pinyin: "tóng gān gòng kǔ", meaning: "share joys and hardships" },
{ word: "接纳", pinyin: "jiē nà", meaning: "to accept" },
{ word: "无怨无悔", pinyin: "wú yuàn wú huǐ", meaning: "no regrets" },
{ word: "千姿百态", pinyin: "qiān zī bǎi tài", meaning: "in many different forms" },
{ word: "空旷", pinyin: "kōng kuàng", meaning: "spacious; open" },
{ word: "患", pinyin: "huàn", meaning: "to suffer from" },
{ word: "失智症", pinyin: "shī zhì zhèng", meaning: "dementia" },
{ word: "寻找", pinyin: "xún zhǎo", meaning: "to look for" },
{ word: "流逝", pinyin: "liú shì", meaning: "to pass; elapse" },
{ word: "嬉戏", pinyin: "xī xì", meaning: "to frolic; to play" },
{ word: "咖喱卜", pinyin: "kā lí bo", meaning: "curry puff" },
{ word: "俏皮", pinyin: "qiào pí", meaning: "playful; lively" },
{ word: "鲜艳", pinyin: "xiān yàn", meaning: "bright-colored; vivid" },
{ word: "承载", pinyin: "chéng zài", meaning: "to bear; to carry" },
{ word: "沉重", pinyin: "chén zhòng", meaning: "heavy; serious" },
{ word: "可谓", pinyin: "kě wèi", meaning: "it can be said" },
{ word: "岛屿", pinyin: "dǎo yǔ", meaning: "island" },
{ word: "海峡", pinyin: "hǎi xiá", meaning: "strait" },
{ word: "历史", pinyin: "lì shǐ", meaning: "history" },
{ word: "挖掘", pinyin: "wā jué", meaning: "to excavate; to explore" },
{ word: "区域", pinyin: "qū yù", meaning: "region" },
{ word: "汇集", pinyin: "huì jí", meaning: "to gather; to assemble" },
{ word: "赋予", pinyin: "fù yǔ", meaning: "to bestow; to give" },
{ word: "海纳百川", pinyin: "hǎi nà bǎi chuān", meaning: "embrace diversity; be broad-minded" },
{ word: "椰浆饭", pinyin: "yē jiāng fàn", meaning: "nasi lemak" },
{ word: "黄姜饭", pinyin: "huáng jiāng fàn", meaning: "turmeric rice" },
{ word: "发芽", pinyin: "fā yá", meaning: "to sprout" },
{ word: "兼容并蓄", pinyin: "jiān róng bìng xù", meaning: "to accommodate all; be inclusive" },
{ word: "携手", pinyin: "xié shǒu", meaning: "to join hands" },
{ word: "得天独厚", pinyin: "dé tiān dú hòu", meaning: "richly endowed by nature" },
{ word: "给予", pinyin: "jǐ yǔ", meaning: "to give; to grant" },
{ word: "婉转", pinyin: "wǎn zhuǎn", meaning: "tactful; indirect" },
{ word: "瞩目", pinyin: "zhǔ mù", meaning: "to attract attention" },
{ word: "求同存异", pinyin: "qiú tóng cún yì", meaning: "seek common ground while reserving differences" },
{ word: "皇帝", pinyin: "huáng dì", meaning: "emperor" },
{ word: "典型", pinyin: "diǎn xíng", meaning: "typical; representative" },
{ word: "普及", pinyin: "pǔ jí", meaning: "to popularize" },
{ word: "真伪", pinyin: "zhēn wěi", meaning: "true or false; authenticity" },
{ word: "步伐", pinyin: "bù fá", meaning: "pace; step" },
{ word: "询问", pinyin: "xún wèn", meaning: "to inquire" },
{ word: "人云亦云", pinyin: "rén yún yì yún", meaning: "to echo others' opinions" },
{ word: "免疫", pinyin: "miǎn yì", meaning: "immunity" },
{ word: "凝聚力", pinyin: "níng jù lì", meaning: "cohesion" },
{ word: "辨别", pinyin: "biàn bié", meaning: "to distinguish; to differentiate" }
    ],
    
    "Level 3": [
        { word: "良好", pinyin: "liáng hǎo", meaning: "good" },
        { word: "人际", pinyin: "rén jì", meaning: "human relationships" },
        { word: "坦率", pinyin: "tǎn shuài", meaning: "frank" },
        { word: "隐瞒", pinyin: "yǐ n mán", meaning: "to conceal" },
        { word: "粗鲁", pinyin: "cū lǔ", meaning: "coarse/rude" },
        { word: "分歧", pinyin: "fēn qí", meaning: "divergent" },
        { word: "矛盾", pinyin: "máo dùn", meaning: "contradiction/conflict" },
        { word: "措施", pinyin: "cuò shī", meaning: "measure" },
        { word: "彼此", pinyin: "bǐ cǐ", meaning: "each other" },
        { word: "诀窍", pinyin: "jué qiào", meaning: "tips/hacks" },
        { word: "融洽", pinyin: "róng qià", meaning: "harmonious" },
        { word: "聆听", pinyin: "líng tīng", meaning: "to listen (respectfully)" },
        { word: "死党", pinyin: "sǐ dǎng", meaning: "best friends" },
        { word: "橱窗", pinyin: "chú chuāng", meaning: "display window" },
        { word: "强迫", pinyin: "qiǎng pò", meaning: "to force" },
        { word: "狭窄", pinyin: "xiá zhǎi", meaning: "narrow" },
        { word: "铅笔盒", pinyin: "qiān bǐ hé", meaning: "pencil case" },
        { word: "捻", pinyin: "niǎn", meaning: "to pinch" },
        { word: "抿", pinyin: "mǐn", meaning: "purse up (lips)" },
        { word: "肺炎", pinyin: "fèi yán", meaning: "pneumonia" },
        { word: "纸屑", pinyin: "zhǐ xiè", meaning: "scraps of paper" },
        { word: "肿瘤", pinyin: "zhǒng liú", meaning: "tumor" },
        { word: "癌症", pinyin: "ái zhèng", meaning: "cancer" },
        { word: "徒劳无功", pinyin: "tú láo wú gōng", meaning: "to work to no avail (idiom)" },
        { word: "擦拭", pinyin: "cā shì", meaning: "to wipe clean" },
        { word: "某", pinyin: "mǒu", meaning: "some" },
        { word: "苍白", pinyin: "cāng bái", meaning: "pale" },
        { word: "鼓掌", pinyin: "gǔ zhǎng", meaning: "to applaud" },
        { word: "忠实", pinyin: "zhōng shí", meaning: "faithful" },
        { word: "不同寻常", pinyin: "bù tóng xún cháng", meaning: "unusual" },
        { word: "痊愈", pinyin: "quán yù", meaning: "to recover completely" },
        { word: "清晰", pinyin: "qīng xī", meaning: "clear" },
        { word: "调剂", pinyin: "tiáo jì", meaning: "to adjust" },
        { word: "目睹", pinyin: "mù dǔ", meaning: "to witness" },
        { word: "鄙夷", pinyin: "bǐ yí", meaning: "to despise" },
        { word: "流淌", pinyin: "liú tǎng", meaning: "to flow" },
        { word: "窗帘", pinyin: "chuāng lián", meaning: "window curtains" },
        { word: "封", pinyin: "fēng", meaning: "to seal" },
        { word: "提心吊胆", pinyin: "tí xīn diào dǎn", meaning: "to be very scared and on edge" },
        { word: "古董", pinyin: "gǔ dǒng", meaning: "antique" },
        { word: "衡量", pinyin: "héng liáng", meaning: "to weigh" },
        { word: "纯洁", pinyin: "chún jié", meaning: "pure" },
        { word: "蔬菜", pinyin: "shū cài", meaning: "vegetables" },
        { word: "麦片", pinyin: "mài piàn", meaning: "oatmeal" },
        { word: "蛋白质", pinyin: "dàn bái zhì", meaning: "protein" },
        { word: "睡眠", pinyin: "shuì mián", meaning: "sleep (noun)" },
        { word: "频率", pinyin: "pín lǜ", meaning: "frequency" },
        { word: "体魄", pinyin: "tǐ pò", meaning: "physique" },
        { word: "韵律", pinyin: "yù nǜ", meaning: "rhythm/cadence" },
        { word: "汲取", pinyin: "jí qǔ", meaning: "to draw/absorb" },
        { word: "敞开", pinyin: "chǎng kāi", meaning: "to open wide" },
        { word: "心扉", pinyin: "xīn fēi", meaning: "door of heart" },
        { word: "缔造", pinyin: "dì zào", meaning: "to create/establish" },
        { word: "聊天", pinyin: "liáo tiān", meaning: "to chat" },
        { word: "郊外", pinyin: "jiāo wài", meaning: "outskirts" },
        { word: "淋漓", pinyin: "lín lí", meaning: "dripping wet" },
        { word: "手札", pinyin: "shǒu zhá", meaning: "personal letter" },
        { word: "抒发", pinyin: "shū fā", meaning: "to express (emotion)" },
        { word: "歇息", pinyin: "xiē xi", meaning: "to rest" },
        { word: "饮茶", pinyin: "yǐ n chá", meaning: "to have tea" },
        { word: "唐", pinyin: "táng", meaning: "Tang dynasty" },
        { word: "磨", pinyin: "mó", meaning: "to rub" },
        { word: "葱", pinyin: "cōng", meaning: "scallion" },
        { word: "橘子", pinyin: "jú zi", meaning: "tangerine" },
        { word: "宋", pinyin: "sòng", meaning: "Song dynasty" },
        { word: "柴", pinyin: "chái", meaning: "firewood" },
        { word: "鼎盛", pinyin: "dǐng shèng", meaning: "peak period" },
        { word: "醋", pinyin: "cù", meaning: "vinegar" },
        { word: "沸水", pinyin: "fèi shuǐ", meaning: "boiling water" },
        { word: "调匀", pinyin: "tiáo yún", meaning: "to blend/stir evenly" },
        { word: "搅拌", pinyin: "jiǎo bàn", meaning: "to stir" },
        { word: "步骤", pinyin: "bù zhòu", meaning: "procedure" },
        { word: "鉴赏", pinyin: "jiàn shǎng", meaning: "to appreciate" },
        { word: "消暑", pinyin: "xiāo shǔ", meaning: "to cool off" },
        { word: "菌", pinyin: "jūn", meaning: "bacteria/fungus" },
        { word: "舞蹈", pinyin: "wǔ dǎo", meaning: "dance" },
        { word: "节奏", pinyin: "jié zòu", meaning: "rhythm" },
        { word: "霹雳舞", pinyin: "pī lì wǔ", meaning: "breakdance" },
        { word: "肌肉", pinyin: "jī ròu", meaning: "muscle" },
        { word: "风靡", pinyin: "fēng mǐ", meaning: "fashionable" },
        { word: "热潮", pinyin: "rè cháo", meaning: "upsurge" },
        { word: "掀起", pinyin: "xiān qǐ", meaning: "to lift / set off" },
        { word: "雨后春笋", pinyin: "yǔ hòu chūn sǔn", meaning: "emerge rapidly" },
        { word: "爆发力", pinyin: "bào fā lì", meaning: "explosive power" },
        { word: "默契", pinyin: "mò qì", meaning: "tacit understanding" },
        { word: "焕发", pinyin: "huàn fā", meaning: "radiant" },
        { word: "真挚", pinyin: "zhēn zhì", meaning: "sincere" },
        { word: "名额", pinyin: "míng é", meaning: "quota" },
        { word: "链接", pinyin: "liàn jiē", meaning: "link" },
        { word: "师傅", pinyin: "shī fu", meaning: "master" },
        { word: "擅长", pinyin: "shàn cháng", meaning: "be good at" },
        { word: "裁缝", pinyin: "cái féng", meaning: "tailor" },
        { word: "编织", pinyin: "biān zhī", meaning: "to weave" },
        { word: "烘焙", pinyin: "hōng bèi", meaning: "to bake" },
        { word: "匠人", pinyin: "jiàng rén", meaning: "craftsman" },
        { word: "讲述", pinyin: "jiǎng shù", meaning: "to talk about" },
        { word: "黎明", pinyin: "lí míng", meaning: "dawn" },
        { word: "禽", pinyin: "qín", meaning: "birds and animals" },
        { word: "苏醒", pinyin: "sū xǐng", meaning: "to wake up" },
        { word: "晚霞", pinyin: "wǎn xiá", meaning: "sunset glow" },
        { word: "添砖加瓦", pinyin: "tiān zhuān jiā wǎ", meaning: "do one's bit to help" },
        { word: "唇齿相依", pinyin: "chún chǐ xiāng yī", meaning: "closely related" },
        { word: "族裔", pinyin: "zú yì", meaning: "ethnic group" },
        { word: "亲戚", pinyin: "qīn qi", meaning: "relative" },
        { word: "援助", pinyin: "yuán shǒu", meaning: "assistance" },
        { word: "侥幸", pinyin: "jiǎo xìng", meaning: "luckily" },
        { word: "慷慨解囊", pinyin: "kāng kǎi jiě náng", meaning: "contribute generously" },
        { word: "渡", pinyin: "dù", meaning: "to cross" },
        { word: "篱笆", pinyin: "lí ba", meaning: "fence" },
        { word: "心力交瘁", pinyin: "xīn lì jiāo cuì", meaning: "mentally and physically exhausted" },
        { word: "雪中送炭", pinyin: "xuě zhōng sòng tàn", meaning: "timely help" },
        { word: "恰好", pinyin: "qià hǎo", meaning: "as it turns out" },
        { word: "弥补", pinyin: "mí bǔ", meaning: "to complement" },
        { word: "谚语", pinyin: "yàn yǔ", meaning: "proverb" },
        { word: "和睦", pinyin: "hé mù", meaning: "peaceful/harmonious" },
        { word: "冷漠", pinyin: "lěng mò", meaning: "cold and indifferent" },
        { word: "挑剔", pinyin: "tiāo ti", meaning: "picky" },
        { word: "网络", pinyin: "wǎng luò", meaning: "network" },
        { word: "锯子", pinyin: "jù zi", meaning: "a saw" },
        { word: "开销", pinyin: "kāi xiāo", meaning: "expenses" },
        { word: "溜", pinyin: "liù", meaning: "to stroll" },
        { word: "栓", pinyin: "shuān", meaning: "tie / stopper" },
        { word: "渠道", pinyin: "qú dào", meaning: "channel" },
        { word: "弊端", pinyin: "bì duān", meaning: "drawback" },
        { word: "培训", pinyin: "péi xùn", meaning: "to train" },
        { word: "阐述", pinyin: "chǎn shù", meaning: "elaborate" },
        { word: "铿锵", pinyin: "kēng qiāng", meaning: "sonorous" },
        { word: "雅俗", pinyin: "yǎ sú", meaning: "elegant and popular" },
        { word: "抑扬顿挫", pinyin: "yì yáng dùn cuò", meaning: "cadence" },
        { word: "僵硬", pinyin: "jiāng yìng", meaning: "stiff" },
        { word: "言简意赅", pinyin: "yán jiǎn yì gāi", meaning: "concise and comprehensive" },
        { word: "啰嗦", pinyin: "luō suo", meaning: "long-winded" },
        { word: "遐想", pinyin: "xià xiǎng", meaning: "reverie" },
        { word: "枯燥", pinyin: "kū zào", meaning: "dry and dull" },
        { word: "筛选", pinyin: "shāi xuǎn", meaning: "to filter" },
        { word: "誉", pinyin: "yù", meaning: "reputation" },
        { word: "润滑剂", pinyin: "rùn huá jì", meaning: "lubricant" },
        { word: "浏览", pinyin: "liú lǎn", meaning: "to browse/skim" },
        { word: "不胜枚举", pinyin: "bú shèng méi jǔ", meaning: "too numerous to mention" },
        { word: "扼腕", pinyin: "è wàn", meaning: "wring hands in regret" },
        { word: "氛围", pinyin: "fēn wéi", meaning: "ambience" },
        { word: "体恤", pinyin: "tǐ xù", meaning: "to empathize" },
        { word: "谦虚", pinyin: "qiān xū", meaning: "modest" },
        { word: "裨益", pinyin: "bì yì", meaning: "benefit" },
        { word: "流言蜚语", pinyin: "liú yán fēi yǔ", meaning: "rumors and slanders" },
        { word: "严峻", pinyin: "yán jùn", meaning: "severe" },
        { word: "扰乱", pinyin: "rǎo luàn", meaning: "to disturb" },
        { word: "甚嚣尘上", pinyin: "shèn xiāo chén shàng", meaning: "tremendous clamor" },
        { word: "基础", pinyin: "jī chǔ", meaning: "base" },
        { word: "涵盖", pinyin: "hán gài", meaning: "to cover" },
        { word: "崛起", pinyin: "jué qǐ", meaning: "rise abruptly" },
        { word: "颠覆", pinyin: "diān fù", meaning: "subvert" },
        { word: "报刊", pinyin: "bào kān", meaning: "newspapers/magazines" },
        { word: "书籍", pinyin: "shū jí", meaning: "books" },
        { word: "传播", pinyin: "chuán bō", meaning: "disseminate" },
        { word: "舶", pinyin: "bó", meaning: "to push aside" },
        { word: "天涯", pinyin: "tiān yá", meaning: "end of the world" },
        { word: "限制", pinyin: "xiàn zhì", meaning: "restrict" },
        { word: "屏幕", pinyin: "píng mù", meaning: "screen" },
        { word: "按钮", pinyin: "àn niǔ", meaning: "push button" },
        { word: "庞大", pinyin: "páng dà", meaning: "huge" },
        { word: "疆界", pinyin: "jiāng jiè", meaning: "border" },
        { word: "阶段", pinyin: "jiē duàn", meaning: "stage" },
        { word: "同侪", pinyin: "tóng chái", meaning: "peer" },
        { word: "撰写", pinyin: "zhuàn xiě", meaning: "to write" },
        { word: "筹备", pinyin: "chóu bèi", meaning: "preparations" },
        { word: "募捐", pinyin: "mù juān", meaning: "solicit contributions" },
        { word: "实践", pinyin: "shí jiàn", meaning: "put into practice" },
        { word: "震撼", pinyin: "zhèn hàn", meaning: "shock" },
        { word: "融会贯通", pinyin: "róng huì guàn tōng", meaning: "master via comprehensive study" },
        { word: "循规蹈矩", pinyin: "xún guī dǎo jǔ", meaning: "follow rules inflexibly" },
        { word: "缅腆", pinyin: "miǎn tiǎn", meaning: "shy" },
        { word: "咨询", pinyin: "zī xún", meaning: "to consult" },
        { word: "数据", pinyin: "shù jù", meaning: "data" },
        { word: "分析", pinyin: "fēn xī", meaning: "analyze" },
        { word: "冰淇淋", pinyin: "bīng qí lín", meaning: "ice cream" },
        { word: "充实", pinyin: "chōng shí", meaning: "enrich/fulfilling" },
        { word: "雄鹰", pinyin: "xióng yīng", meaning: "male eagle" },
        { word: "渺小", pinyin: "miǎo xiǎo", meaning: "tiny" },
        { word: "坐井观天", pinyin: "zuò jǐng guān tiān", meaning: "narrow-minded" },
        { word: "自鸣得意", pinyin: "zì míng dé yì", meaning: "think highly of oneself" },
        { word: "孤陋寡闻", pinyin: "gū lòu guǎ wén", meaning: "ignorant" },
        { word: "奥妙", pinyin: "ào miào", meaning: "secret" },
        { word: "寓言", pinyin: "yù yán", meaning: "fable" },
        { word: "桨", pinyin: "jiǎng", meaning: "oar" },
        { word: "浅尝辄止", pinyin: "qiǎn cháng zhé zhǐ", meaning: "dabble and stop" },
        { word: "哲学", pinyin: "zhé xué", meaning: "philosophy" },
        { word: "比喻", pinyin: "bǐ yù", meaning: "metaphor/simile" },
        { word: "热忱", pinyin: "rè chén", meaning: "zeal" },
        { word: "清澈", pinyin: "qīng chè", meaning: "clear liquid" },
        { word: "持之以恒", pinyin: "chí zhī yǐ héng", meaning: "persevere" },
        { word: "干涸", pinyin: "gān hé", meaning: "to dry up" },
        { word: "浇灌", pinyin: "jiāo guàn", meaning: "to water" },
        { word: "落伍", pinyin: "luò wǔ", meaning: "fall behind" },
        { word: "楷模", pinyin: "kǎi mó", meaning: "model" },
        { word: "孜孜不倦", pinyin: "zī zī bú juàn", meaning: "continuous effort" },
        { word: "敷衍", pinyin: "fū yǎn", meaning: "half-heartedly" },
        { word: "逆水行舟", pinyin: "nì shuǐ xíng zhōu", meaning: "navigating against current" },
        { word: "淘汰", pinyin: "táo tài", meaning: "wash out" },
        { word: "佐证", pinyin: "zuǒ zhèng", meaning: "evidence" },
        { word: "平庸", pinyin: "píng yōng", meaning: "mediocre" },
        { word: "岂", pinyin: "qǐ", meaning: "how? (emphatic)" },
        { word: "诠释", pinyin: "quán shì", meaning: "interpret" },
        { word: "抛锚", pinyin: "pāo máo", meaning: "anchor or breakdown" },
        { word: "郁闷", pinyin: "yù mèn", meaning: "depressed/gloomy" },
        { word: "逗", pinyin: "dòu", meaning: "tease" },
        { word: "叼", pinyin: "diāo", meaning: "hold with mouth" },
        { word: "挑战", pinyin: "tiǎo zhàn", meaning: "challenge" },
        { word: "绊", pinyin: "bàn", meaning: "trip" },
        { word: "雀跃", pinyin: "què yuè", meaning: "excited" },
        { word: "攀登", pinyin: "pān dēng", meaning: "climb" },
        { word: "山脉", pinyin: "shān mài", meaning: "mountain range" },
        { word: "宇宙", pinyin: "yǔ zhòu", meaning: "universe" },
        { word: "跋涉", pinyin: "bá shè", meaning: "trek/trudge" },
        { word: "体验", pinyin: "tǐ yàn", meaning: "experience" },
        { word: "牵挂", pinyin: "qiān guà", meaning: "worry about" },
        { word: "喉咙", pinyin: "hóu lóng", meaning: "throat" },
        { word: "唤", pinyin: "huàn", meaning: "call" },
        { word: "绽放", pinyin: "zhàn fàng", meaning: "blossom" },
        { word: "绷", pinyin: "bēng", meaning: "draw tight" },
        { word: "一般", pinyin: "yì bān", meaning: "same" },
        { word: "无奈", pinyin: "wú nài", meaning: "helpless" },
        { word: "寺庙", pinyin: "sì miào", meaning: "temple" },
        { word: "幽静", pinyin: "yōu jìng", meaning: "quiet" },
        { word: "诧异", pinyin: "chà yì", meaning: "surprised" },
        { word: "贱", pinyin: "jiàn", meaning: "inexpensive" },
        { word: "哽咽", pinyin: "gěng yè", meaning: "choke with emotion" },
        { word: "眼眶", pinyin: "yǎn kuàng", meaning: "eye socket" },
        { word: "隆重", pinyin: "lóng zhòng", meaning: "grand" },
        { word: "咀嚼", pinyin: "jǔ jué", meaning: "chew" },
        { word: "诅咒", pinyin: "zǔ zhòu", meaning: "curse" },
        { word: "洋溢", pinyin: "yáng yì", meaning: "brimming with" },
        { word: "慈祥", pinyin: "cí xiáng", meaning: "kindly" },
        { word: "潭", pinyin: "tán", meaning: "deep pool" },
        { word: "教授", pinyin: "jiào shòu", meaning: "professor" },
        { word: "割舍", pinyin: "gē shě", meaning: "give up" },
        { word: "磋商", pinyin: "cuō shāng", meaning: "to consult; to negotiate" },
{ word: "均衡", pinyin: "jūn héng", meaning: "balanced; equilibrium" },
{ word: "享受", pinyin: "xiǎng shòu", meaning: "to enjoy" },
{ word: "所谓", pinyin: "suǒ wèi", meaning: "so-called" },
{ word: "源远流长", pinyin: "yuán yuǎn liú cháng", meaning: "to have a long history" },
{ word: "异军突起", pinyin: "yì jūn tū qǐ", meaning: "to rise suddenly as a new force" },
{ word: "五花八门", pinyin: "wǔ huā bā mén", meaning: "varied; all kinds of" },
{ word: "鲜为人知", pinyin: "xiǎn wéi rén zhī", meaning: "rarely known" },
{ word: "宵夜", pinyin: "xiāo yè", meaning: "late-night snack" },
{ word: "艰难", pinyin: "jiān nán", meaning: "difficult; hard" },
{ word: "营造", pinyin: "yíng zào", meaning: "to build; to create" },
{ word: "计较", pinyin: "jì jiào", meaning: "to fuss over; to haggle over" },
{ word: "划算", pinyin: "huá suàn", meaning: "worth it; cost-effective" },
{ word: "久而久之", pinyin: "jiǔ ér jiǔ zhī", meaning: "as time passes" },
{ word: "畅所欲言", pinyin: "chàng suǒ yù yán", meaning: "to speak freely" },
{ word: "尊重", pinyin: "zūn zhòng", meaning: "to respect" },
{ word: "广泛", pinyin: "guǎng fàn", meaning: "wide; extensive" },
{ word: "导致", pinyin: "dǎo zhì", meaning: "to lead to; to cause" },
{ word: "前所未有", pinyin: "qián suǒ wèi yǒu", meaning: "unprecedented" },
{ word: "创建", pinyin: "chuàng jiàn", meaning: "to establish; to create" },
{ word: "贯穿", pinyin: "guàn chuān", meaning: "to run through; to permeate" },
{ word: "勇于", pinyin: "yǒng yú", meaning: "to have the courage to" },
{ word: "九牛一毛", pinyin: "jiǔ niú yī máo", meaning: "a drop in the bucket" },
{ word: "层出不穷", pinyin: "céng chū bù qióng", meaning: "to emerge one after another endlessly" },
{ word: "信任", pinyin: "xìn rèn", meaning: "to trust; trust" },
{ word: "依赖", pinyin: "yī lài", meaning: "to rely on; dependence" },
{ word: "搬迁", pinyin: "bān qiān", meaning: "to move; to relocate" },
{ word: "孝顺", pinyin: "xiào shùn", meaning: "filial; to be filial" },
{ word: "探望", pinyin: "tàn wàng", meaning: "to visit" },
{ word: "谅解", pinyin: "liàng jiě", meaning: "to understand; to forgive" },
{ word: "折磨", pinyin: "zhé mó", meaning: "to torment; suffering" },
{ word: "神圣", pinyin: "shén shèng", meaning: "sacred; holy" },
{ word: "介意", pinyin: "jiè yì", meaning: "to mind; to care about" },
{ word: "演奏", pinyin: "yǎn zòu", meaning: "to perform music" }
    ],
    
    "Level 4": [
    { word: "责无旁贷", pinyin: "zé wú páng dài", meaning: "duty-bound; obligated" },
    { word: "分忧", pinyin: "fēn yōu", meaning: "to share worries; relieve burden" },
    { word: "残障", pinyin: "cán zhàng", meaning: "disability; handicap" },
    { word: "聘请", pinyin: "pìn qǐng", meaning: "to hire; employ" },
    { word: "同工同酬", pinyin: "tóng gōng tóng chóu", meaning: "equal pay for equal work" },
    { word: "权利", pinyin: "quán lì", meaning: "rights" },
    { word: "雇主", pinyin: "gù zhǔ", meaning: "employer" },
    { word: "纠纷", pinyin: "jiū fēn", meaning: "dispute; conflict" },
    { word: "小贩", pinyin: "xiǎo fàn", meaning: "hawker; vendor" },
    { word: "摊位", pinyin: "tān wèi", meaning: "stall; booth" },
    { word: "呵护", pinyin: "hē hù", meaning: "to care for; protect" },
    { word: "缓解", pinyin: "huǎn jiě", meaning: "to alleviate; ease" },
    { word: "乞丐", pinyin: "qǐ gài", meaning: "beggar" },
    { word: "祈求", pinyin: "qí qiú", meaning: "to pray for; beseech" },
    { word: "褴褛", pinyin: "lán lǚ", meaning: "ragged; tattered" },
    { word: "跪", pinyin: "guì", meaning: "to kneel" },
    { word: "肮脏", pinyin: "āng zāng", meaning: "dirty; filthy" },
    { word: "贫穷", pinyin: "pín qióng", meaning: "poor; impoverished" },
    { word: "赤裸裸", pinyin: "chì luǒ luǒ", meaning: "naked; bare; blatant" },
    { word: "距离", pinyin: "jù lí", meaning: "distance" },
    { word: "慈悲", pinyin: "cí bēi", meaning: "compassion; mercy" },
    { word: "阻挡", pinyin: "zǔ dǎng", meaning: "to block; obstruct" },
    { word: "肆无忌惮", pinyin: "sì wú jì dàn", meaning: "unscrupulous; without restraint" },
    { word: "革履", pinyin: "gé lǚ", meaning: "leather shoes" },
    { word: "侦探", pinyin: "zhēn tàn", meaning: "detective" },
    { word: "仁慈", pinyin: "rén cí", meaning: "benevolent; kind" },
    { word: "叩头", pinyin: "kòu tóu", meaning: "to kowtow; bow deeply" },
    { word: "残疾", pinyin: "cán jí", meaning: "disabled; handicapped" },
    { word: "质朴", pinyin: "zhì pǔ", meaning: "simple; plain; honest" },
    { word: "大概", pinyin: "dà gài", meaning: "probably; roughly" },
    { word: "晓得", pinyin: "xiǎo de", meaning: "to know; understand" },
    { word: "蓦然", pinyin: "mò rán", meaning: "suddenly; unexpectedly" },
    { word: "推心置腹", pinyin: "tuī xīn zhì fù", meaning: "to be frank and sincere" },
    { word: "否则", pinyin: "fǒu zé", meaning: "otherwise; or else" },
    { word: "感恩", pinyin: "gǎn ēn", meaning: "to be grateful" },
    { word: "匆匆", pinyin: "cōng cōng", meaning: "hurriedly; hastily" },
    { word: "婴儿", pinyin: "yīng ér", meaning: "baby; infant" },
    { word: "翅膀", pinyin: "chì bǎng", meaning: "wing" },
    { word: "呈献", pinyin: "chéng xiàn", meaning: "to present; offer" },
    { word: "扣人心弦", pinyin: "kòu rén xīn xián", meaning: "gripping; touching" },
    { word: "爱恋", pinyin: "ài liàn", meaning: "love; romantic attachment" },
    { word: "唏嘘", pinyin: "xī xū", meaning: "to sigh; lament" },
    { word: "著名", pinyin: "zhù míng", meaning: "famous; renowned" },
    { word: "兴旺", pinyin: "xīng wàng", meaning: "prosperous; thriving" },
    { word: "负荷", pinyin: "fù hè", meaning: "load; burden" },
    { word: "反映", pinyin: "fǎn yìng", meaning: "to reflect; show" },
    { word: "岔路口", pinyin: "chà lù kǒu", meaning: "crossroads; junction" },
    { word: "惆怅", pinyin: "chóu chàng", meaning: "melancholy; dejected" },
    { word: "紧凑", pinyin: "jǐn còu", meaning: "compact; tight" },
    { word: "小卒", pinyin: "xiǎo zú", meaning: "pawn; minor character" },
    { word: "兴衰", pinyin: "xīng shuāi", meaning: "rise and fall" },
    { word: "轿子", pinyin: "jiào zi", meaning: "sedan chair; palanquin" },
    { word: "何况", pinyin: "hé kuàng", meaning: "let alone; not to mention" },
    { word: "耻笑", pinyin: "chǐ xiào", meaning: "to ridicule; mock" },
    { word: "搀扶", pinyin: "chān fú", meaning: "to support; help" },
    { word: "罢了", pinyin: "bà le", meaning: "that's all; nothing more" },
    { word: "姊妹", pinyin: "zǐ mèi", meaning: "sisters" },
    { word: "顽劣", pinyin: "wán liè", meaning: "naughty; mischievous" },
    { word: "溺爱", pinyin: "nì ài", meaning: "to spoil; dote on" },
    { word: "颈项", pinyin: "jǐng xiàng", meaning: "neck; nape" },
    { word: "鬓", pinyin: "bìn", meaning: "temples; sideburns" },
    { word: "桃瓣", pinyin: "táo bàn", meaning: "peach petal" },
    { word: "重逢", pinyin: "chóng féng", meaning: "to reunite; meet again" },
    { word: "稀罕", pinyin: "xī han", meaning: "rare; precious" },
    { word: "拜见", pinyin: "bài jiàn", meaning: "to pay respects; visit" },
    { word: "面善", pinyin: "miàn shàn", meaning: "familiar-looking" },
    { word: "大吃一惊", pinyin: "dà chī yī jīng", meaning: "greatly surprised" },
    { word: "三顾茅庐", pinyin: "sān gù máo lú", meaning: "three visits to the cottage" },
    { word: "争霸", pinyin: "zhēng bà", meaning: "to compete for supremacy" },
    { word: "足智多谋", pinyin: "zú zhì duō móu", meaning: "resourceful; wise" },
    { word: "起伏", pinyin: "qǐ fú", meaning: "ups and downs" },
    { word: "斥责", pinyin: "chì zé", meaning: "to scold; rebuke" },
    { word: "严寒", pinyin: "yán hán", meaning: "severe cold" },
    { word: "恳请", pinyin: "kěn qǐng", meaning: "to earnestly request" },
    { word: "心直口快", pinyin: "xīn zhí kǒu kuài", meaning: "frank and outspoken" },
    { word: "酿", pinyin: "niàng", meaning: "to brew; cause" },
    { word: "涌", pinyin: "yǒng", meaning: "to surge; gush" },
    { word: "繁殖", pinyin: "fán zhí", meaning: "to reproduce; breed" },
    { word: "饲料", pinyin: "sì liào", meaning: "feed; fodder" },
    { word: "佳肴", pinyin: "jiā yáo", meaning: "delicacy; fine food" },
    { word: "啃", pinyin: "kěn", meaning: "to gnaw; bite" },
    { word: "入侵", pinyin: "rù qīn", meaning: "to invade; intrude" },
    { word: "盎然", pinyin: "àng rán", meaning: "abundant; full of" },
    { word: "砍伐", pinyin: "kǎn fá", meaning: "to cut down; fell" },
    { word: "栖息", pinyin: "qī xī", meaning: "to inhabit; roost" },
    { word: "牢记", pinyin: "láo jì", meaning: "to remember firmly" },
    { word: "勿", pinyin: "wù", meaning: "don't; must not" },
    { word: "惩罚", pinyin: "chéng fá", meaning: "to punish; penalize" },
    { word: "平衡", pinyin: "píng héng", meaning: "balance; equilibrium" },
    { word: "珍稀", pinyin: "zhēn xī", meaning: "rare and precious" },
    { word: "茂密", pinyin: "mào mì", meaning: "dense; thick" },
    { word: "恶劣", pinyin: "è liè", meaning: "harsh; severe" },
    { word: "浸泡", pinyin: "jìn pào", meaning: "to soak; immerse" },
    { word: "牺牲", pinyin: "xī shēng", meaning: "to sacrifice" },
    { word: "锐减", pinyin: "ruì jiǎn", meaning: "to decrease sharply" },
    { word: "保育", pinyin: "bǎo yù", meaning: "conservation; protection" },
    { word: "储存", pinyin: "chǔ cún", meaning: "to store; save" },
    { word: "身躯", pinyin: "shēn qū", meaning: "body; physique" },
    { word: "侵蚀", pinyin: "qīn shí", meaning: "to erode; corrode" },
    { word: "空隙", pinyin: "kōng xì", meaning: "gap; space" },
    { word: "堤", pinyin: "dī", meaning: "embankment; dike" },
    { word: "貌不惊人", pinyin: "mào bù jīng rén", meaning: "unremarkable appearance" },
    { word: "窥视", pinyin: "kuī shì", meaning: "to peep; spy on" },
    { word: "宣布", pinyin: "xuān bù", meaning: "to announce; declare" },
    { word: "狩猎", pinyin: "shòu liè", meaning: "to hunt" },
    { word: "饥饿", pinyin: "jī è", meaning: "hungry; starved" },
    { word: "糟蹋", pinyin: "zāo tà", meaning: "to waste; ruin" },
    { word: "毁灭", pinyin: "huǐ miè", meaning: "to destroy; ruin" },
    { word: "罪魁祸首", pinyin: "zuì kuí huò shǒu", meaning: "chief culprit" },
    { word: "竞争", pinyin: "jìng zhēng", meaning: "to compete" },
    { word: "袭击", pinyin: "xí jī", meaning: "to attack; assault" },
    { word: "违背", pinyin: "wéi bèi", meaning: "to violate; go against" },
    { word: "拼搏", pinyin: "pīn bó", meaning: "to struggle; fight hard" },
    { word: "面目全非", "pinyin": "miàn mù quán fēi", "meaning": "completely changed" },
    { word: "举措", "pinyin": "jǔ cuò", "meaning": "measures; steps" },
        { word: "踪影", pinyin: "zōng yǐng", meaning: "trace; sign" },
{ word: "联盟", pinyin: "lián méng", meaning: "alliance; coalition" },
{ word: "迄今", pinyin: "qì jīn", meaning: "up to now; so far" },
{ word: "蜿蜒", pinyin: "wān yán", meaning: "winding; meandering" },
{ word: "辽阔", pinyin: "liáo kuò", meaning: "vast; extensive" },
{ word: "诸多", pinyin: "zhū duō", meaning: "many; numerous" },
{ word: "古迹", pinyin: "gǔ jì", meaning: "historic site; ancient monument" },
{ word: "雕刻", pinyin: "diāo kè", meaning: "to carve; sculpture" },
{ word: "啧啧称奇", pinyin: "zé zé chēng qí", meaning: "to click one's tongue in wonder" },
{ word: "赞叹", pinyin: "zàn tàn", meaning: "to praise; to gasp in admiration" },
{ word: "底蕴", pinyin: "dǐ yùn", meaning: "cultural depth; accumulated richness" },
{ word: "灿烂", pinyin: "càn làn", meaning: "brilliant; splendid" },
{ word: "金碧辉煌", pinyin: "jīn bì huī huáng", meaning: "splendid and magnificent" },
{ word: "绚丽", pinyin: "xuàn lì", meaning: "gorgeous; splendid" },
{ word: "壮观", pinyin: "zhuàng guān", meaning: "spectacular; magnificent" },
{ word: "高耸", pinyin: "gāo sǒng", meaning: "towering; lofty" },
{ word: "颇", pinyin: "pō", meaning: "quite; rather" },
{ word: "独树一帜", pinyin: "dú shù yī zhì", meaning: "to stand out with a unique style" },
{ word: "赋税", pinyin: "fù shuì", meaning: "taxes" },
{ word: "揭竿而起", pinyin: "jiē gān ér qǐ", meaning: "to rise in rebellion" },
{ word: "暴虐", pinyin: "bào nüè", meaning: "cruel and tyrannical" },
{ word: "葬送", pinyin: "zàng sòng", meaning: "to ruin; to bury" },
{ word: "推卸", pinyin: "tuī xiè", meaning: "to shirk; to evade responsibility" },
{ word: "停滞", pinyin: "tíng zhì", meaning: "to stagnate" },
{ word: "趾高气扬", pinyin: "zhǐ gāo qì yáng", meaning: "arrogant; self-important" },
{ word: "谦逊", pinyin: "qiān xùn", meaning: "modest; humble" },
{ word: "梦寐以求", pinyin: "mèng mèi yǐ qiú", meaning: "to long for; dream of" },
{ word: "昌盛", pinyin: "chāng shèng", meaning: "prosperous; flourishing" },
{ word: "自知之明", pinyin: "zì zhī zhī míng", meaning: "self-awareness" },
{ word: "忍无可忍", pinyin: "rěn wú kě rěn", meaning: "unable to endure anymore" },
{ word: "一无是处", pinyin: "yī wú shì chù", meaning: "good for nothing" },
{ word: "协作", pinyin: "xié zuò", meaning: "to cooperate; collaboration" },
{ word: "论坛", pinyin: "lùn tán", meaning: "forum" },
{ word: "毋庸讳言", pinyin: "wú yōng huì yán", meaning: "there is no need to deny; frankly speaking" },
{ word: "棘手", pinyin: "jí shǒu", meaning: "tricky; difficult to handle" },
{ word: "肆虐", pinyin: "sì nüè", meaning: "to wreak havoc" },
{ word: "谋求", pinyin: "móu qiú", meaning: "to seek; to strive for" },
{ word: "里程碑", pinyin: "lǐ chéng bēi", meaning: "milestone" },
{ word: "开拓", pinyin: "kāi tuò", meaning: "to open up; to develop" },
{ word: "先驱", pinyin: "xiān qū", meaning: "pioneer" },
{ word: "气馁", pinyin: "qì něi", meaning: "discouraged; to lose heart" },
{ word: "出类拔萃", pinyin: "chū lèi bá cuì", meaning: "outstanding; exceptional" },
{ word: "韧性", pinyin: "rèn xìng", meaning: "resilience; toughness" },
{ word: "浩瀚", pinyin: "hào hàn", meaning: "vast; boundless" },
{ word: "天方夜谭", pinyin: "tiān fāng yè tán", meaning: "fantasy; incredible tale" },
{ word: "百折不挠", pinyin: "bǎi zhé bù náo", meaning: "unyielding; indomitable" },
{ word: "研发", pinyin: "yán fā", meaning: "research and development" },
{ word: "畅销", pinyin: "chàng xiāo", meaning: "best-selling" },
{ word: "贬", pinyin: "biǎn", meaning: "to devalue; to demote; to criticize" },
{ word: "粮食", pinyin: "liáng shi", meaning: "grain; food supply" },
{ word: "豁达", pinyin: "huò dá", meaning: "open-minded; optimistic" },
{ word: "满腔", pinyin: "mǎn qiāng", meaning: "filled with; full of" },
{ word: "霜", pinyin: "shuāng", meaning: "frost" },
{ word: "遣", pinyin: "qiǎn", meaning: "to dispatch; to send" },
{ word: "挽", pinyin: "wǎn", meaning: "to pull; to draw back; to retrieve" },
{ word: "豪迈", pinyin: "háo mài", meaning: "bold and generous; heroic" },
{ word: "慷慨激昂", pinyin: "kāng kǎi jī áng", meaning: "impassioned; fervent" },
{ word: "勉励", pinyin: "miǎn lì", meaning: "to encourage" },
{ word: "朝廷", pinyin: "cháo tíng", meaning: "imperial court" },
{ word: "笔锋", pinyin: "bǐ fēng", meaning: "style of writing; force of writing" },
{ word: "扎", pinyin: "zhā", meaning: "to prick; to pierce" },
{ word: "喧腾", pinyin: "xuān téng", meaning: "noisy and bustling" },
{ word: "感悟", pinyin: "gǎn wù", meaning: "insight; realization" },
{ word: "崭新", pinyin: "zhǎn xīn", meaning: "brand-new" },
{ word: "迥然", pinyin: "jiǒng rán", meaning: "vastly different" },
{ word: "奋斗", pinyin: "fèn dòu", meaning: "to strive; to struggle" },
{ word: "崎岖", pinyin: "qí qū", meaning: "rugged; bumpy" },
{ word: "抵达", pinyin: "dǐ dá", meaning: "to arrive" }
]
};
